/**
 * CPM API
 * Public API for CPM
 *
 * OpenAPI spec version: V1.0
 * Contact: info@addison.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package instantreports.api;

import instantreports.ApiException;
import instantreports.model.Member;
import instantreports.model.Organization;
import instantreports.model.Tenant;
import org.junit.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DirectoryApi
 */
public class DirectoryApiTest {

    private final DirectoryApi api = new DirectoryApi();

    
    /**
     * get: directory/member
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void directoryMemberGetTest() throws ApiException {
        String authorization = null;
        String organization = null;
        String where = null;
        String order = null;
        String skip = null;
        String take = null;
        // Member response = api.directoryMemberGet(authorization, organization, where, order, skip, take);

        // TODO: test validations
    }
    
    /**
     * delete: directory/member
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void directoryMemberResourceIdDeleteTest() throws ApiException {
        String authorization = null;
        String organization = null;
        String resourceId = null;
        Member body = null;
        // api.directoryMemberResourceIdDelete(authorization, organization, resourceId, body);

        // TODO: test validations
    }
    
    /**
     * get: directory/member/id
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void directoryMemberResourceIdGetTest() throws ApiException {
        String authorization = null;
        String organization = null;
        String resourceId = null;
        // Member response = api.directoryMemberResourceIdGet(authorization, organization, resourceId);

        // TODO: test validations
    }
    
    /**
     * put: directory/member
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void directoryMemberResourceIdPutTest() throws ApiException {
        String authorization = null;
        String organization = null;
        String resourceId = null;
        Member body = null;
        // api.directoryMemberResourceIdPut(authorization, organization, resourceId, body);

        // TODO: test validations
    }
    
    /**
     * get: directory/organization
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void directoryOrganizationGetTest() throws ApiException {
        String authorization = null;
        String organization = null;
        String where = null;
        String order = null;
        String skip = null;
        String take = null;
        // Organization response = api.directoryOrganizationGet(authorization, organization, where, order, skip, take);

        // TODO: test validations
    }
    
    /**
     * delete: directory/organization
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void directoryOrganizationResourceIdDeleteTest() throws ApiException {
        String authorization = null;
        String organization = null;
        String resourceId = null;
        Organization body = null;
        // api.directoryOrganizationResourceIdDelete(authorization, organization, resourceId, body);

        // TODO: test validations
    }
    
    /**
     * get: directory/organization/id
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void directoryOrganizationResourceIdGetTest() throws ApiException {
        String authorization = null;
        String organization = null;
        String resourceId = null;
        // Organization response = api.directoryOrganizationResourceIdGet(authorization, organization, resourceId);

        // TODO: test validations
    }
    
    /**
     * put: directory/organization
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void directoryOrganizationResourceIdPutTest() throws ApiException {
        String authorization = null;
        String organization = null;
        String resourceId = null;
        Organization body = null;
        // api.directoryOrganizationResourceIdPut(authorization, organization, resourceId, body);

        // TODO: test validations
    }
    
    /**
     * post: directory/member
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void directoryResourcePostTest() throws ApiException {
        String authorization = null;
        String organization = null;
        String resource = null;
        Member body = null;
        // api.directoryResourcePost(authorization, organization, resource, body);

        // TODO: test validations
    }
    
    /**
     * get: directory/tenant
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void directoryTenantGetTest() throws ApiException {
        String authorization = null;
        String organization = null;
        String where = null;
        String order = null;
        String skip = null;
        String take = null;
        // Tenant response = api.directoryTenantGet(authorization, organization, where, order, skip, take);

        // TODO: test validations
    }
    
    /**
     * get: directory/tenant/id
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void directoryTenantResourceIdGetTest() throws ApiException {
        String authorization = null;
        String organization = null;
        String resourceId = null;
        // Tenant response = api.directoryTenantResourceIdGet(authorization, organization, resourceId);

        // TODO: test validations
    }
    
}
