/**
 * CPM API
 * Public API for CPM
 *
 * OpenAPI spec version: V1.0
 * Contact: info@addison.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package instantreports.api;

import instantreports.ApiException;
import instantreports.model.Lohnart;
import instantreports.model.Lohnartenplan;
import instantreports.model.Lohnartmerged;
import instantreports.model.Template;
import org.junit.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PayrollschemaApi
 */
public class PayrollschemaApiTest {

    private final PayrollschemaApi api = new PayrollschemaApi();

    
    /**
     * get: payroll_schema/lohnart
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void payrollSchemaLohnartGetTest() throws ApiException {
        String authorization = null;
        String organization = null;
        String where = null;
        String order = null;
        String skip = null;
        String take = null;
        // Lohnart response = api.payrollSchemaLohnartGet(authorization, organization, where, order, skip, take);

        // TODO: test validations
    }
    
    /**
     * get: payroll_schema/lohnart/id
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void payrollSchemaLohnartResourceIdGetTest() throws ApiException {
        String authorization = null;
        String organization = null;
        String resourceId = null;
        // Lohnart response = api.payrollSchemaLohnartResourceIdGet(authorization, organization, resourceId);

        // TODO: test validations
    }
    
    /**
     * put: payroll_schema/lohnart
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void payrollSchemaLohnartResourceIdPutTest() throws ApiException {
        String authorization = null;
        String organization = null;
        String resourceId = null;
        Lohnart body = null;
        // api.payrollSchemaLohnartResourceIdPut(authorization, organization, resourceId, body);

        // TODO: test validations
    }
    
    /**
     * get: payroll_schema/lohnartenplan
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void payrollSchemaLohnartenplanGetTest() throws ApiException {
        String authorization = null;
        String organization = null;
        String where = null;
        String order = null;
        String skip = null;
        String take = null;
        // Lohnartenplan response = api.payrollSchemaLohnartenplanGet(authorization, organization, where, order, skip, take);

        // TODO: test validations
    }
    
    /**
     * get: payroll_schema/lohnartenplan/id
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void payrollSchemaLohnartenplanResourceIdGetTest() throws ApiException {
        String authorization = null;
        String organization = null;
        String resourceId = null;
        // Lohnartenplan response = api.payrollSchemaLohnartenplanResourceIdGet(authorization, organization, resourceId);

        // TODO: test validations
    }
    
    /**
     * put: payroll_schema/lohnartenplan
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void payrollSchemaLohnartenplanResourceIdPutTest() throws ApiException {
        String authorization = null;
        String organization = null;
        String resourceId = null;
        Lohnartenplan body = null;
        // api.payrollSchemaLohnartenplanResourceIdPut(authorization, organization, resourceId, body);

        // TODO: test validations
    }
    
    /**
     * get: payroll_schema/lohnartmerged
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void payrollSchemaLohnartmergedGetTest() throws ApiException {
        String authorization = null;
        String organization = null;
        String where = null;
        String order = null;
        String skip = null;
        String take = null;
        // Lohnartmerged response = api.payrollSchemaLohnartmergedGet(authorization, organization, where, order, skip, take);

        // TODO: test validations
    }
    
    /**
     * get: payroll_schema/lohnartmerged/id
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void payrollSchemaLohnartmergedResourceIdGetTest() throws ApiException {
        String authorization = null;
        String organization = null;
        String resourceId = null;
        // Lohnartmerged response = api.payrollSchemaLohnartmergedResourceIdGet(authorization, organization, resourceId);

        // TODO: test validations
    }
    
    /**
     * put: payroll_schema/lohnartmerged
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void payrollSchemaLohnartmergedResourceIdPutTest() throws ApiException {
        String authorization = null;
        String organization = null;
        String resourceId = null;
        Lohnartmerged body = null;
        // api.payrollSchemaLohnartmergedResourceIdPut(authorization, organization, resourceId, body);

        // TODO: test validations
    }
    
    /**
     * post: payroll_schema/lohnart
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void payrollSchemaResourcePostTest() throws ApiException {
        String authorization = null;
        String organization = null;
        String resource = null;
        Lohnart body = null;
        // api.payrollSchemaResourcePost(authorization, organization, resource, body);

        // TODO: test validations
    }
    
    /**
     * get: payroll_schema/template
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void payrollSchemaTemplateGetTest() throws ApiException {
        String authorization = null;
        String organization = null;
        String where = null;
        String order = null;
        String skip = null;
        String take = null;
        // Template response = api.payrollSchemaTemplateGet(authorization, organization, where, order, skip, take);

        // TODO: test validations
    }
    
    /**
     * get: payroll_schema/template/id
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void payrollSchemaTemplateResourceIdGetTest() throws ApiException {
        String authorization = null;
        String organization = null;
        String resourceId = null;
        // Template response = api.payrollSchemaTemplateResourceIdGet(authorization, organization, resourceId);

        // TODO: test validations
    }
    
    /**
     * put: payroll_schema/template
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void payrollSchemaTemplateResourceIdPutTest() throws ApiException {
        String authorization = null;
        String organization = null;
        String resourceId = null;
        Template body = null;
        // api.payrollSchemaTemplateResourceIdPut(authorization, organization, resourceId, body);

        // TODO: test validations
    }
    
}
