/**
 * CPM API
 * Public API for CPM
 *
 * OpenAPI spec version: V1.0
 * Contact: info@addison.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package instantreports.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.LocalDate;


/**
 * ActivityApi
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2018-05-03T09:33:53.199+02:00")
public class ActivityApi   {
  @SerializedName("activityTaxonomy")
  private String activityTaxonomy = null;

  @SerializedName("milestoneName")
  private String milestoneName = null;

  @SerializedName("responsibleRoleName")
  private String responsibleRoleName = null;

  @SerializedName("effectiveResponsibleRoleName")
  private String effectiveResponsibleRoleName = null;

  @SerializedName("taskDueState")
  private Integer taskDueState = null;

  @SerializedName("appLink")
  private String appLink = null;

  @SerializedName("showInMe")
  private Boolean showInMe = null;

  @SerializedName("taskState")
  private Integer taskState = null;

  @SerializedName("processChainPosition")
  private Long processChainPosition = null;

  @SerializedName("processName")
  private String processName = null;

  @SerializedName("firmIsResponsible")
  private Boolean firmIsResponsible = null;

  @SerializedName("serviceAgreementId")
  private String serviceAgreementId = null;

  @SerializedName("duedate")
  private LocalDate duedate = null;

  @SerializedName("responsible")
  private String responsible = null;

  @SerializedName("processOriginId")
  private String processOriginId = null;

  @SerializedName("taskName")
  private String taskName = null;

  @SerializedName("isVirtual")
  private Boolean isVirtual = null;

  @SerializedName("clientProposedState")
  private Integer clientProposedState = null;

  @SerializedName("serviceAgreementName")
  private String serviceAgreementName = null;

  @SerializedName("taskId")
  private Long taskId = null;

  @SerializedName("processInstanceName")
  private String processInstanceName = null;

  public ActivityApi activityTaxonomy(String activityTaxonomy) {
    this.activityTaxonomy = activityTaxonomy;
    return this;
  }

   /**
   * 
   * @return activityTaxonomy
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getActivityTaxonomy() {
    return activityTaxonomy;
  }

  public void setActivityTaxonomy(String activityTaxonomy) {
    this.activityTaxonomy = activityTaxonomy;
  }

  public ActivityApi milestoneName(String milestoneName) {
    this.milestoneName = milestoneName;
    return this;
  }

   /**
   * 
   * @return milestoneName
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getMilestoneName() {
    return milestoneName;
  }

  public void setMilestoneName(String milestoneName) {
    this.milestoneName = milestoneName;
  }

  public ActivityApi responsibleRoleName(String responsibleRoleName) {
    this.responsibleRoleName = responsibleRoleName;
    return this;
  }

   /**
   * 
   * @return responsibleRoleName
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getResponsibleRoleName() {
    return responsibleRoleName;
  }

  public void setResponsibleRoleName(String responsibleRoleName) {
    this.responsibleRoleName = responsibleRoleName;
  }

  public ActivityApi effectiveResponsibleRoleName(String effectiveResponsibleRoleName) {
    this.effectiveResponsibleRoleName = effectiveResponsibleRoleName;
    return this;
  }

   /**
   * 
   * @return effectiveResponsibleRoleName
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getEffectiveResponsibleRoleName() {
    return effectiveResponsibleRoleName;
  }

  public void setEffectiveResponsibleRoleName(String effectiveResponsibleRoleName) {
    this.effectiveResponsibleRoleName = effectiveResponsibleRoleName;
  }

  public ActivityApi taskDueState(Integer taskDueState) {
    this.taskDueState = taskDueState;
    return this;
  }

   /**
   * 
   * @return taskDueState
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Integer getTaskDueState() {
    return taskDueState;
  }

  public void setTaskDueState(Integer taskDueState) {
    this.taskDueState = taskDueState;
  }

  public ActivityApi appLink(String appLink) {
    this.appLink = appLink;
    return this;
  }

   /**
   * 
   * @return appLink
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getAppLink() {
    return appLink;
  }

  public void setAppLink(String appLink) {
    this.appLink = appLink;
  }

  public ActivityApi showInMe(Boolean showInMe) {
    this.showInMe = showInMe;
    return this;
  }

   /**
   * 
   * @return showInMe
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Boolean getShowInMe() {
    return showInMe;
  }

  public void setShowInMe(Boolean showInMe) {
    this.showInMe = showInMe;
  }

  public ActivityApi taskState(Integer taskState) {
    this.taskState = taskState;
    return this;
  }

   /**
   * 
   * @return taskState
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Integer getTaskState() {
    return taskState;
  }

  public void setTaskState(Integer taskState) {
    this.taskState = taskState;
  }

  public ActivityApi processChainPosition(Long processChainPosition) {
    this.processChainPosition = processChainPosition;
    return this;
  }

   /**
   * 
   * @return processChainPosition
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Long getProcessChainPosition() {
    return processChainPosition;
  }

  public void setProcessChainPosition(Long processChainPosition) {
    this.processChainPosition = processChainPosition;
  }

  public ActivityApi processName(String processName) {
    this.processName = processName;
    return this;
  }

   /**
   * 
   * @return processName
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getProcessName() {
    return processName;
  }

  public void setProcessName(String processName) {
    this.processName = processName;
  }

  public ActivityApi firmIsResponsible(Boolean firmIsResponsible) {
    this.firmIsResponsible = firmIsResponsible;
    return this;
  }

   /**
   * 
   * @return firmIsResponsible
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Boolean getFirmIsResponsible() {
    return firmIsResponsible;
  }

  public void setFirmIsResponsible(Boolean firmIsResponsible) {
    this.firmIsResponsible = firmIsResponsible;
  }

  public ActivityApi serviceAgreementId(String serviceAgreementId) {
    this.serviceAgreementId = serviceAgreementId;
    return this;
  }

   /**
   * 
   * @return serviceAgreementId
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getServiceAgreementId() {
    return serviceAgreementId;
  }

  public void setServiceAgreementId(String serviceAgreementId) {
    this.serviceAgreementId = serviceAgreementId;
  }

  public ActivityApi duedate(LocalDate duedate) {
    this.duedate = duedate;
    return this;
  }

   /**
   * 
   * @return duedate
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public LocalDate getDuedate() {
    return duedate;
  }

  public void setDuedate(LocalDate duedate) {
    this.duedate = duedate;
  }

  public ActivityApi responsible(String responsible) {
    this.responsible = responsible;
    return this;
  }

   /**
   * 
   * @return responsible
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getResponsible() {
    return responsible;
  }

  public void setResponsible(String responsible) {
    this.responsible = responsible;
  }

  public ActivityApi processOriginId(String processOriginId) {
    this.processOriginId = processOriginId;
    return this;
  }

   /**
   * 
   * @return processOriginId
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getProcessOriginId() {
    return processOriginId;
  }

  public void setProcessOriginId(String processOriginId) {
    this.processOriginId = processOriginId;
  }

  public ActivityApi taskName(String taskName) {
    this.taskName = taskName;
    return this;
  }

   /**
   * 
   * @return taskName
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getTaskName() {
    return taskName;
  }

  public void setTaskName(String taskName) {
    this.taskName = taskName;
  }

  public ActivityApi isVirtual(Boolean isVirtual) {
    this.isVirtual = isVirtual;
    return this;
  }

   /**
   * 
   * @return isVirtual
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Boolean getIsVirtual() {
    return isVirtual;
  }

  public void setIsVirtual(Boolean isVirtual) {
    this.isVirtual = isVirtual;
  }

  public ActivityApi clientProposedState(Integer clientProposedState) {
    this.clientProposedState = clientProposedState;
    return this;
  }

   /**
   * 
   * @return clientProposedState
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Integer getClientProposedState() {
    return clientProposedState;
  }

  public void setClientProposedState(Integer clientProposedState) {
    this.clientProposedState = clientProposedState;
  }

  public ActivityApi serviceAgreementName(String serviceAgreementName) {
    this.serviceAgreementName = serviceAgreementName;
    return this;
  }

   /**
   * 
   * @return serviceAgreementName
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getServiceAgreementName() {
    return serviceAgreementName;
  }

  public void setServiceAgreementName(String serviceAgreementName) {
    this.serviceAgreementName = serviceAgreementName;
  }

  public ActivityApi taskId(Long taskId) {
    this.taskId = taskId;
    return this;
  }

   /**
   * 
   * @return taskId
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Long getTaskId() {
    return taskId;
  }

  public void setTaskId(Long taskId) {
    this.taskId = taskId;
  }

  public ActivityApi processInstanceName(String processInstanceName) {
    this.processInstanceName = processInstanceName;
    return this;
  }

   /**
   * 
   * @return processInstanceName
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getProcessInstanceName() {
    return processInstanceName;
  }

  public void setProcessInstanceName(String processInstanceName) {
    this.processInstanceName = processInstanceName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ActivityApi activityApi = (ActivityApi) o;
    return Objects.equals(this.activityTaxonomy, activityApi.activityTaxonomy) &&
        Objects.equals(this.milestoneName, activityApi.milestoneName) &&
        Objects.equals(this.responsibleRoleName, activityApi.responsibleRoleName) &&
        Objects.equals(this.effectiveResponsibleRoleName, activityApi.effectiveResponsibleRoleName) &&
        Objects.equals(this.taskDueState, activityApi.taskDueState) &&
        Objects.equals(this.appLink, activityApi.appLink) &&
        Objects.equals(this.showInMe, activityApi.showInMe) &&
        Objects.equals(this.taskState, activityApi.taskState) &&
        Objects.equals(this.processChainPosition, activityApi.processChainPosition) &&
        Objects.equals(this.processName, activityApi.processName) &&
        Objects.equals(this.firmIsResponsible, activityApi.firmIsResponsible) &&
        Objects.equals(this.serviceAgreementId, activityApi.serviceAgreementId) &&
        Objects.equals(this.duedate, activityApi.duedate) &&
        Objects.equals(this.responsible, activityApi.responsible) &&
        Objects.equals(this.processOriginId, activityApi.processOriginId) &&
        Objects.equals(this.taskName, activityApi.taskName) &&
        Objects.equals(this.isVirtual, activityApi.isVirtual) &&
        Objects.equals(this.clientProposedState, activityApi.clientProposedState) &&
        Objects.equals(this.serviceAgreementName, activityApi.serviceAgreementName) &&
        Objects.equals(this.taskId, activityApi.taskId) &&
        Objects.equals(this.processInstanceName, activityApi.processInstanceName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(activityTaxonomy, milestoneName, responsibleRoleName, effectiveResponsibleRoleName, taskDueState, appLink, showInMe, taskState, processChainPosition, processName, firmIsResponsible, serviceAgreementId, duedate, responsible, processOriginId, taskName, isVirtual, clientProposedState, serviceAgreementName, taskId, processInstanceName);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ActivityApi {\n");
    
    sb.append("    activityTaxonomy: ").append(toIndentedString(activityTaxonomy)).append("\n");
    sb.append("    milestoneName: ").append(toIndentedString(milestoneName)).append("\n");
    sb.append("    responsibleRoleName: ").append(toIndentedString(responsibleRoleName)).append("\n");
    sb.append("    effectiveResponsibleRoleName: ").append(toIndentedString(effectiveResponsibleRoleName)).append("\n");
    sb.append("    taskDueState: ").append(toIndentedString(taskDueState)).append("\n");
    sb.append("    appLink: ").append(toIndentedString(appLink)).append("\n");
    sb.append("    showInMe: ").append(toIndentedString(showInMe)).append("\n");
    sb.append("    taskState: ").append(toIndentedString(taskState)).append("\n");
    sb.append("    processChainPosition: ").append(toIndentedString(processChainPosition)).append("\n");
    sb.append("    processName: ").append(toIndentedString(processName)).append("\n");
    sb.append("    firmIsResponsible: ").append(toIndentedString(firmIsResponsible)).append("\n");
    sb.append("    serviceAgreementId: ").append(toIndentedString(serviceAgreementId)).append("\n");
    sb.append("    duedate: ").append(toIndentedString(duedate)).append("\n");
    sb.append("    responsible: ").append(toIndentedString(responsible)).append("\n");
    sb.append("    processOriginId: ").append(toIndentedString(processOriginId)).append("\n");
    sb.append("    taskName: ").append(toIndentedString(taskName)).append("\n");
    sb.append("    isVirtual: ").append(toIndentedString(isVirtual)).append("\n");
    sb.append("    clientProposedState: ").append(toIndentedString(clientProposedState)).append("\n");
    sb.append("    serviceAgreementName: ").append(toIndentedString(serviceAgreementName)).append("\n");
    sb.append("    taskId: ").append(toIndentedString(taskId)).append("\n");
    sb.append("    processInstanceName: ").append(toIndentedString(processInstanceName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

