/**
 * CPM API
 * Public API for CPM
 *
 * OpenAPI spec version: V1.0
 * Contact: info@addison.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package instantreports.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * BuchungskreisDataApi
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2018-05-03T09:33:53.199+02:00")
public class BuchungskreisDataApi   {
  @SerializedName("opVerwaltung")
  private Boolean opVerwaltung = null;

  @SerializedName("kostAnbindung")
  private Boolean kostAnbindung = null;

  @SerializedName("farbeRGB")
  private String farbeRGB = null;

  @SerializedName("bezeichnung")
  private String bezeichnung = null;

  @SerializedName("nummer")
  private Integer nummer = null;

  public BuchungskreisDataApi opVerwaltung(Boolean opVerwaltung) {
    this.opVerwaltung = opVerwaltung;
    return this;
  }

   /**
   *  (filterable/sortable)
   * @return opVerwaltung
  **/
  @ApiModelProperty(example = "null", required = true, value = " (filterable/sortable)")
  public Boolean getOpVerwaltung() {
    return opVerwaltung;
  }

  public void setOpVerwaltung(Boolean opVerwaltung) {
    this.opVerwaltung = opVerwaltung;
  }

  public BuchungskreisDataApi kostAnbindung(Boolean kostAnbindung) {
    this.kostAnbindung = kostAnbindung;
    return this;
  }

   /**
   *  (filterable/sortable)
   * @return kostAnbindung
  **/
  @ApiModelProperty(example = "null", required = true, value = " (filterable/sortable)")
  public Boolean getKostAnbindung() {
    return kostAnbindung;
  }

  public void setKostAnbindung(Boolean kostAnbindung) {
    this.kostAnbindung = kostAnbindung;
  }

  public BuchungskreisDataApi farbeRGB(String farbeRGB) {
    this.farbeRGB = farbeRGB;
    return this;
  }

   /**
   * 
   * @return farbeRGB
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getFarbeRGB() {
    return farbeRGB;
  }

  public void setFarbeRGB(String farbeRGB) {
    this.farbeRGB = farbeRGB;
  }

  public BuchungskreisDataApi bezeichnung(String bezeichnung) {
    this.bezeichnung = bezeichnung;
    return this;
  }

   /**
   *  (filterable/sortable)
   * @return bezeichnung
  **/
  @ApiModelProperty(example = "null", required = true, value = " (filterable/sortable)")
  public String getBezeichnung() {
    return bezeichnung;
  }

  public void setBezeichnung(String bezeichnung) {
    this.bezeichnung = bezeichnung;
  }

  public BuchungskreisDataApi nummer(Integer nummer) {
    this.nummer = nummer;
    return this;
  }

   /**
   *  (filterable/sortable)
   * @return nummer
  **/
  @ApiModelProperty(example = "null", required = true, value = " (filterable/sortable)")
  public Integer getNummer() {
    return nummer;
  }

  public void setNummer(Integer nummer) {
    this.nummer = nummer;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BuchungskreisDataApi buchungskreisDataApi = (BuchungskreisDataApi) o;
    return Objects.equals(this.opVerwaltung, buchungskreisDataApi.opVerwaltung) &&
        Objects.equals(this.kostAnbindung, buchungskreisDataApi.kostAnbindung) &&
        Objects.equals(this.farbeRGB, buchungskreisDataApi.farbeRGB) &&
        Objects.equals(this.bezeichnung, buchungskreisDataApi.bezeichnung) &&
        Objects.equals(this.nummer, buchungskreisDataApi.nummer);
  }

  @Override
  public int hashCode() {
    return Objects.hash(opVerwaltung, kostAnbindung, farbeRGB, bezeichnung, nummer);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BuchungskreisDataApi {\n");
    
    sb.append("    opVerwaltung: ").append(toIndentedString(opVerwaltung)).append("\n");
    sb.append("    kostAnbindung: ").append(toIndentedString(kostAnbindung)).append("\n");
    sb.append("    farbeRGB: ").append(toIndentedString(farbeRGB)).append("\n");
    sb.append("    bezeichnung: ").append(toIndentedString(bezeichnung)).append("\n");
    sb.append("    nummer: ").append(toIndentedString(nummer)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

