/**
 * CPM API
 * Public API for CPM
 *
 * OpenAPI spec version: V1.0
 * Contact: info@addison.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package instantreports.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.LocalDate;


/**
 * EmployeeActivityApi
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2018-05-03T09:33:53.199+02:00")
public class EmployeeActivityApi   {
  @SerializedName("clientId")
  private String clientId = null;

  @SerializedName("taskIsCompleted")
  private Boolean taskIsCompleted = null;

  @SerializedName("clientName")
  private String clientName = null;

  @SerializedName("milestoneName")
  private String milestoneName = null;

  @SerializedName("responsibleRoleName")
  private String responsibleRoleName = null;

  @SerializedName("dueDate")
  private LocalDate dueDate = null;

  @SerializedName("milestoneId")
  private Long milestoneId = null;

  @SerializedName("responsibleRoleId")
  private String responsibleRoleId = null;

  @SerializedName("assignedEmployeeId")
  private String assignedEmployeeId = null;

  @SerializedName("taskState")
  private Integer taskState = null;

  @SerializedName("processId")
  private String processId = null;

  @SerializedName("processName")
  private String processName = null;

  @SerializedName("serviceAgreementId")
  private String serviceAgreementId = null;

  @SerializedName("clientCode")
  private String clientCode = null;

  @SerializedName("taskName")
  private String taskName = null;

  @SerializedName("assignedEmployeeName")
  private String assignedEmployeeName = null;

  @SerializedName("taskId")
  private Long taskId = null;

  @SerializedName("serviceAgreementName")
  private String serviceAgreementName = null;

  @SerializedName("processInstanceName")
  private String processInstanceName = null;

  public EmployeeActivityApi clientId(String clientId) {
    this.clientId = clientId;
    return this;
  }

   /**
   * 
   * @return clientId
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getClientId() {
    return clientId;
  }

  public void setClientId(String clientId) {
    this.clientId = clientId;
  }

  public EmployeeActivityApi taskIsCompleted(Boolean taskIsCompleted) {
    this.taskIsCompleted = taskIsCompleted;
    return this;
  }

   /**
   * 
   * @return taskIsCompleted
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Boolean getTaskIsCompleted() {
    return taskIsCompleted;
  }

  public void setTaskIsCompleted(Boolean taskIsCompleted) {
    this.taskIsCompleted = taskIsCompleted;
  }

  public EmployeeActivityApi clientName(String clientName) {
    this.clientName = clientName;
    return this;
  }

   /**
   * 
   * @return clientName
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getClientName() {
    return clientName;
  }

  public void setClientName(String clientName) {
    this.clientName = clientName;
  }

  public EmployeeActivityApi milestoneName(String milestoneName) {
    this.milestoneName = milestoneName;
    return this;
  }

   /**
   * 
   * @return milestoneName
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getMilestoneName() {
    return milestoneName;
  }

  public void setMilestoneName(String milestoneName) {
    this.milestoneName = milestoneName;
  }

  public EmployeeActivityApi responsibleRoleName(String responsibleRoleName) {
    this.responsibleRoleName = responsibleRoleName;
    return this;
  }

   /**
   * 
   * @return responsibleRoleName
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getResponsibleRoleName() {
    return responsibleRoleName;
  }

  public void setResponsibleRoleName(String responsibleRoleName) {
    this.responsibleRoleName = responsibleRoleName;
  }

  public EmployeeActivityApi dueDate(LocalDate dueDate) {
    this.dueDate = dueDate;
    return this;
  }

   /**
   * 
   * @return dueDate
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public LocalDate getDueDate() {
    return dueDate;
  }

  public void setDueDate(LocalDate dueDate) {
    this.dueDate = dueDate;
  }

  public EmployeeActivityApi milestoneId(Long milestoneId) {
    this.milestoneId = milestoneId;
    return this;
  }

   /**
   * 
   * @return milestoneId
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Long getMilestoneId() {
    return milestoneId;
  }

  public void setMilestoneId(Long milestoneId) {
    this.milestoneId = milestoneId;
  }

  public EmployeeActivityApi responsibleRoleId(String responsibleRoleId) {
    this.responsibleRoleId = responsibleRoleId;
    return this;
  }

   /**
   * 
   * @return responsibleRoleId
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getResponsibleRoleId() {
    return responsibleRoleId;
  }

  public void setResponsibleRoleId(String responsibleRoleId) {
    this.responsibleRoleId = responsibleRoleId;
  }

  public EmployeeActivityApi assignedEmployeeId(String assignedEmployeeId) {
    this.assignedEmployeeId = assignedEmployeeId;
    return this;
  }

   /**
   * 
   * @return assignedEmployeeId
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getAssignedEmployeeId() {
    return assignedEmployeeId;
  }

  public void setAssignedEmployeeId(String assignedEmployeeId) {
    this.assignedEmployeeId = assignedEmployeeId;
  }

  public EmployeeActivityApi taskState(Integer taskState) {
    this.taskState = taskState;
    return this;
  }

   /**
   * 
   * @return taskState
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Integer getTaskState() {
    return taskState;
  }

  public void setTaskState(Integer taskState) {
    this.taskState = taskState;
  }

  public EmployeeActivityApi processId(String processId) {
    this.processId = processId;
    return this;
  }

   /**
   * 
   * @return processId
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getProcessId() {
    return processId;
  }

  public void setProcessId(String processId) {
    this.processId = processId;
  }

  public EmployeeActivityApi processName(String processName) {
    this.processName = processName;
    return this;
  }

   /**
   * 
   * @return processName
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getProcessName() {
    return processName;
  }

  public void setProcessName(String processName) {
    this.processName = processName;
  }

  public EmployeeActivityApi serviceAgreementId(String serviceAgreementId) {
    this.serviceAgreementId = serviceAgreementId;
    return this;
  }

   /**
   * 
   * @return serviceAgreementId
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getServiceAgreementId() {
    return serviceAgreementId;
  }

  public void setServiceAgreementId(String serviceAgreementId) {
    this.serviceAgreementId = serviceAgreementId;
  }

  public EmployeeActivityApi clientCode(String clientCode) {
    this.clientCode = clientCode;
    return this;
  }

   /**
   * 
   * @return clientCode
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getClientCode() {
    return clientCode;
  }

  public void setClientCode(String clientCode) {
    this.clientCode = clientCode;
  }

  public EmployeeActivityApi taskName(String taskName) {
    this.taskName = taskName;
    return this;
  }

   /**
   * 
   * @return taskName
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getTaskName() {
    return taskName;
  }

  public void setTaskName(String taskName) {
    this.taskName = taskName;
  }

  public EmployeeActivityApi assignedEmployeeName(String assignedEmployeeName) {
    this.assignedEmployeeName = assignedEmployeeName;
    return this;
  }

   /**
   * 
   * @return assignedEmployeeName
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getAssignedEmployeeName() {
    return assignedEmployeeName;
  }

  public void setAssignedEmployeeName(String assignedEmployeeName) {
    this.assignedEmployeeName = assignedEmployeeName;
  }

  public EmployeeActivityApi taskId(Long taskId) {
    this.taskId = taskId;
    return this;
  }

   /**
   * 
   * @return taskId
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Long getTaskId() {
    return taskId;
  }

  public void setTaskId(Long taskId) {
    this.taskId = taskId;
  }

  public EmployeeActivityApi serviceAgreementName(String serviceAgreementName) {
    this.serviceAgreementName = serviceAgreementName;
    return this;
  }

   /**
   * 
   * @return serviceAgreementName
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getServiceAgreementName() {
    return serviceAgreementName;
  }

  public void setServiceAgreementName(String serviceAgreementName) {
    this.serviceAgreementName = serviceAgreementName;
  }

  public EmployeeActivityApi processInstanceName(String processInstanceName) {
    this.processInstanceName = processInstanceName;
    return this;
  }

   /**
   * 
   * @return processInstanceName
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getProcessInstanceName() {
    return processInstanceName;
  }

  public void setProcessInstanceName(String processInstanceName) {
    this.processInstanceName = processInstanceName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EmployeeActivityApi employeeActivityApi = (EmployeeActivityApi) o;
    return Objects.equals(this.clientId, employeeActivityApi.clientId) &&
        Objects.equals(this.taskIsCompleted, employeeActivityApi.taskIsCompleted) &&
        Objects.equals(this.clientName, employeeActivityApi.clientName) &&
        Objects.equals(this.milestoneName, employeeActivityApi.milestoneName) &&
        Objects.equals(this.responsibleRoleName, employeeActivityApi.responsibleRoleName) &&
        Objects.equals(this.dueDate, employeeActivityApi.dueDate) &&
        Objects.equals(this.milestoneId, employeeActivityApi.milestoneId) &&
        Objects.equals(this.responsibleRoleId, employeeActivityApi.responsibleRoleId) &&
        Objects.equals(this.assignedEmployeeId, employeeActivityApi.assignedEmployeeId) &&
        Objects.equals(this.taskState, employeeActivityApi.taskState) &&
        Objects.equals(this.processId, employeeActivityApi.processId) &&
        Objects.equals(this.processName, employeeActivityApi.processName) &&
        Objects.equals(this.serviceAgreementId, employeeActivityApi.serviceAgreementId) &&
        Objects.equals(this.clientCode, employeeActivityApi.clientCode) &&
        Objects.equals(this.taskName, employeeActivityApi.taskName) &&
        Objects.equals(this.assignedEmployeeName, employeeActivityApi.assignedEmployeeName) &&
        Objects.equals(this.taskId, employeeActivityApi.taskId) &&
        Objects.equals(this.serviceAgreementName, employeeActivityApi.serviceAgreementName) &&
        Objects.equals(this.processInstanceName, employeeActivityApi.processInstanceName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(clientId, taskIsCompleted, clientName, milestoneName, responsibleRoleName, dueDate, milestoneId, responsibleRoleId, assignedEmployeeId, taskState, processId, processName, serviceAgreementId, clientCode, taskName, assignedEmployeeName, taskId, serviceAgreementName, processInstanceName);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EmployeeActivityApi {\n");
    
    sb.append("    clientId: ").append(toIndentedString(clientId)).append("\n");
    sb.append("    taskIsCompleted: ").append(toIndentedString(taskIsCompleted)).append("\n");
    sb.append("    clientName: ").append(toIndentedString(clientName)).append("\n");
    sb.append("    milestoneName: ").append(toIndentedString(milestoneName)).append("\n");
    sb.append("    responsibleRoleName: ").append(toIndentedString(responsibleRoleName)).append("\n");
    sb.append("    dueDate: ").append(toIndentedString(dueDate)).append("\n");
    sb.append("    milestoneId: ").append(toIndentedString(milestoneId)).append("\n");
    sb.append("    responsibleRoleId: ").append(toIndentedString(responsibleRoleId)).append("\n");
    sb.append("    assignedEmployeeId: ").append(toIndentedString(assignedEmployeeId)).append("\n");
    sb.append("    taskState: ").append(toIndentedString(taskState)).append("\n");
    sb.append("    processId: ").append(toIndentedString(processId)).append("\n");
    sb.append("    processName: ").append(toIndentedString(processName)).append("\n");
    sb.append("    serviceAgreementId: ").append(toIndentedString(serviceAgreementId)).append("\n");
    sb.append("    clientCode: ").append(toIndentedString(clientCode)).append("\n");
    sb.append("    taskName: ").append(toIndentedString(taskName)).append("\n");
    sb.append("    assignedEmployeeName: ").append(toIndentedString(assignedEmployeeName)).append("\n");
    sb.append("    taskId: ").append(toIndentedString(taskId)).append("\n");
    sb.append("    serviceAgreementName: ").append(toIndentedString(serviceAgreementName)).append("\n");
    sb.append("    processInstanceName: ").append(toIndentedString(processInstanceName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

