/**
 * CPM API
 * Public API for CPM
 *
 * OpenAPI spec version: V1.0
 * Contact: info@addison.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package instantreports.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * EntlohnungApi
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2018-05-03T09:33:53.199+02:00")
public class EntlohnungApi   {
  @SerializedName("sonderurlaub")
  private String sonderurlaub = null;

  @SerializedName("kostentraegerNummer")
  private Long kostentraegerNummer = null;

  @SerializedName("stundenlohn")
  private String stundenlohn = null;

  @SerializedName("arbeitszeitWoechentlich")
  private String arbeitszeitWoechentlich = null;

  @SerializedName("kostenstelleBezeichnung")
  private String kostenstelleBezeichnung = null;

  @SerializedName("erhaltenerUrlaub")
  private String erhaltenerUrlaub = null;

  @SerializedName("monatslohn")
  private String monatslohn = null;

  @SerializedName("urlaubsanspruch")
  private String urlaubsanspruch = null;

  @SerializedName("kostenstelleNummer")
  private Long kostenstelleNummer = null;

  @SerializedName("woechentlicheArbeitszeitAbweichend")
  private Boolean woechentlicheArbeitszeitAbweichend = null;

  @SerializedName("kostentraegerBezeichnung")
  private String kostentraegerBezeichnung = null;

  @SerializedName("urlaubsanspruchLaufendesJahr")
  private String urlaubsanspruchLaufendesJahr = null;

  @SerializedName("resturlaub")
  private String resturlaub = null;

  public EntlohnungApi sonderurlaub(String sonderurlaub) {
    this.sonderurlaub = sonderurlaub;
    return this;
  }

   /**
   * 
   * @return sonderurlaub
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getSonderurlaub() {
    return sonderurlaub;
  }

  public void setSonderurlaub(String sonderurlaub) {
    this.sonderurlaub = sonderurlaub;
  }

  public EntlohnungApi kostentraegerNummer(Long kostentraegerNummer) {
    this.kostentraegerNummer = kostentraegerNummer;
    return this;
  }

   /**
   * 
   * @return kostentraegerNummer
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getKostentraegerNummer() {
    return kostentraegerNummer;
  }

  public void setKostentraegerNummer(Long kostentraegerNummer) {
    this.kostentraegerNummer = kostentraegerNummer;
  }

  public EntlohnungApi stundenlohn(String stundenlohn) {
    this.stundenlohn = stundenlohn;
    return this;
  }

   /**
   * 
   * @return stundenlohn
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getStundenlohn() {
    return stundenlohn;
  }

  public void setStundenlohn(String stundenlohn) {
    this.stundenlohn = stundenlohn;
  }

  public EntlohnungApi arbeitszeitWoechentlich(String arbeitszeitWoechentlich) {
    this.arbeitszeitWoechentlich = arbeitszeitWoechentlich;
    return this;
  }

   /**
   * 
   * @return arbeitszeitWoechentlich
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getArbeitszeitWoechentlich() {
    return arbeitszeitWoechentlich;
  }

  public void setArbeitszeitWoechentlich(String arbeitszeitWoechentlich) {
    this.arbeitszeitWoechentlich = arbeitszeitWoechentlich;
  }

  public EntlohnungApi kostenstelleBezeichnung(String kostenstelleBezeichnung) {
    this.kostenstelleBezeichnung = kostenstelleBezeichnung;
    return this;
  }

   /**
   * 
   * @return kostenstelleBezeichnung
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getKostenstelleBezeichnung() {
    return kostenstelleBezeichnung;
  }

  public void setKostenstelleBezeichnung(String kostenstelleBezeichnung) {
    this.kostenstelleBezeichnung = kostenstelleBezeichnung;
  }

  public EntlohnungApi erhaltenerUrlaub(String erhaltenerUrlaub) {
    this.erhaltenerUrlaub = erhaltenerUrlaub;
    return this;
  }

   /**
   * 
   * @return erhaltenerUrlaub
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getErhaltenerUrlaub() {
    return erhaltenerUrlaub;
  }

  public void setErhaltenerUrlaub(String erhaltenerUrlaub) {
    this.erhaltenerUrlaub = erhaltenerUrlaub;
  }

  public EntlohnungApi monatslohn(String monatslohn) {
    this.monatslohn = monatslohn;
    return this;
  }

   /**
   * 
   * @return monatslohn
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getMonatslohn() {
    return monatslohn;
  }

  public void setMonatslohn(String monatslohn) {
    this.monatslohn = monatslohn;
  }

  public EntlohnungApi urlaubsanspruch(String urlaubsanspruch) {
    this.urlaubsanspruch = urlaubsanspruch;
    return this;
  }

   /**
   * 
   * @return urlaubsanspruch
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getUrlaubsanspruch() {
    return urlaubsanspruch;
  }

  public void setUrlaubsanspruch(String urlaubsanspruch) {
    this.urlaubsanspruch = urlaubsanspruch;
  }

  public EntlohnungApi kostenstelleNummer(Long kostenstelleNummer) {
    this.kostenstelleNummer = kostenstelleNummer;
    return this;
  }

   /**
   * 
   * @return kostenstelleNummer
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getKostenstelleNummer() {
    return kostenstelleNummer;
  }

  public void setKostenstelleNummer(Long kostenstelleNummer) {
    this.kostenstelleNummer = kostenstelleNummer;
  }

  public EntlohnungApi woechentlicheArbeitszeitAbweichend(Boolean woechentlicheArbeitszeitAbweichend) {
    this.woechentlicheArbeitszeitAbweichend = woechentlicheArbeitszeitAbweichend;
    return this;
  }

   /**
   * 
   * @return woechentlicheArbeitszeitAbweichend
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getWoechentlicheArbeitszeitAbweichend() {
    return woechentlicheArbeitszeitAbweichend;
  }

  public void setWoechentlicheArbeitszeitAbweichend(Boolean woechentlicheArbeitszeitAbweichend) {
    this.woechentlicheArbeitszeitAbweichend = woechentlicheArbeitszeitAbweichend;
  }

  public EntlohnungApi kostentraegerBezeichnung(String kostentraegerBezeichnung) {
    this.kostentraegerBezeichnung = kostentraegerBezeichnung;
    return this;
  }

   /**
   * 
   * @return kostentraegerBezeichnung
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getKostentraegerBezeichnung() {
    return kostentraegerBezeichnung;
  }

  public void setKostentraegerBezeichnung(String kostentraegerBezeichnung) {
    this.kostentraegerBezeichnung = kostentraegerBezeichnung;
  }

  public EntlohnungApi urlaubsanspruchLaufendesJahr(String urlaubsanspruchLaufendesJahr) {
    this.urlaubsanspruchLaufendesJahr = urlaubsanspruchLaufendesJahr;
    return this;
  }

   /**
   * 
   * @return urlaubsanspruchLaufendesJahr
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getUrlaubsanspruchLaufendesJahr() {
    return urlaubsanspruchLaufendesJahr;
  }

  public void setUrlaubsanspruchLaufendesJahr(String urlaubsanspruchLaufendesJahr) {
    this.urlaubsanspruchLaufendesJahr = urlaubsanspruchLaufendesJahr;
  }

  public EntlohnungApi resturlaub(String resturlaub) {
    this.resturlaub = resturlaub;
    return this;
  }

   /**
   * 
   * @return resturlaub
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getResturlaub() {
    return resturlaub;
  }

  public void setResturlaub(String resturlaub) {
    this.resturlaub = resturlaub;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EntlohnungApi entlohnungApi = (EntlohnungApi) o;
    return Objects.equals(this.sonderurlaub, entlohnungApi.sonderurlaub) &&
        Objects.equals(this.kostentraegerNummer, entlohnungApi.kostentraegerNummer) &&
        Objects.equals(this.stundenlohn, entlohnungApi.stundenlohn) &&
        Objects.equals(this.arbeitszeitWoechentlich, entlohnungApi.arbeitszeitWoechentlich) &&
        Objects.equals(this.kostenstelleBezeichnung, entlohnungApi.kostenstelleBezeichnung) &&
        Objects.equals(this.erhaltenerUrlaub, entlohnungApi.erhaltenerUrlaub) &&
        Objects.equals(this.monatslohn, entlohnungApi.monatslohn) &&
        Objects.equals(this.urlaubsanspruch, entlohnungApi.urlaubsanspruch) &&
        Objects.equals(this.kostenstelleNummer, entlohnungApi.kostenstelleNummer) &&
        Objects.equals(this.woechentlicheArbeitszeitAbweichend, entlohnungApi.woechentlicheArbeitszeitAbweichend) &&
        Objects.equals(this.kostentraegerBezeichnung, entlohnungApi.kostentraegerBezeichnung) &&
        Objects.equals(this.urlaubsanspruchLaufendesJahr, entlohnungApi.urlaubsanspruchLaufendesJahr) &&
        Objects.equals(this.resturlaub, entlohnungApi.resturlaub);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sonderurlaub, kostentraegerNummer, stundenlohn, arbeitszeitWoechentlich, kostenstelleBezeichnung, erhaltenerUrlaub, monatslohn, urlaubsanspruch, kostenstelleNummer, woechentlicheArbeitszeitAbweichend, kostentraegerBezeichnung, urlaubsanspruchLaufendesJahr, resturlaub);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EntlohnungApi {\n");
    
    sb.append("    sonderurlaub: ").append(toIndentedString(sonderurlaub)).append("\n");
    sb.append("    kostentraegerNummer: ").append(toIndentedString(kostentraegerNummer)).append("\n");
    sb.append("    stundenlohn: ").append(toIndentedString(stundenlohn)).append("\n");
    sb.append("    arbeitszeitWoechentlich: ").append(toIndentedString(arbeitszeitWoechentlich)).append("\n");
    sb.append("    kostenstelleBezeichnung: ").append(toIndentedString(kostenstelleBezeichnung)).append("\n");
    sb.append("    erhaltenerUrlaub: ").append(toIndentedString(erhaltenerUrlaub)).append("\n");
    sb.append("    monatslohn: ").append(toIndentedString(monatslohn)).append("\n");
    sb.append("    urlaubsanspruch: ").append(toIndentedString(urlaubsanspruch)).append("\n");
    sb.append("    kostenstelleNummer: ").append(toIndentedString(kostenstelleNummer)).append("\n");
    sb.append("    woechentlicheArbeitszeitAbweichend: ").append(toIndentedString(woechentlicheArbeitszeitAbweichend)).append("\n");
    sb.append("    kostentraegerBezeichnung: ").append(toIndentedString(kostentraegerBezeichnung)).append("\n");
    sb.append("    urlaubsanspruchLaufendesJahr: ").append(toIndentedString(urlaubsanspruchLaufendesJahr)).append("\n");
    sb.append("    resturlaub: ").append(toIndentedString(resturlaub)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

