/**
 * CPM API
 * Public API for CPM
 *
 * OpenAPI spec version: V1.0
 * Contact: info@addison.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package instantreports.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import instantreports.model.LocationApi;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;


/**
 * Firm
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2018-05-03T09:33:53.199+02:00")
public class Firm   {
  @SerializedName("locationList")
  private List<LocationApi> locationList = new ArrayList<LocationApi>();

  @SerializedName("name")
  private String name = null;

  @SerializedName("vatId")
  private String vatId = null;

  @SerializedName("nameAffix")
  private String nameAffix = null;

  @SerializedName("id")
  private String id = null;

  public Firm locationList(List<LocationApi> locationList) {
    this.locationList = locationList;
    return this;
  }

  public Firm addLocationListItem(LocationApi locationListItem) {
    this.locationList.add(locationListItem);
    return this;
  }

   /**
   * Get locationList
   * @return locationList
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<LocationApi> getLocationList() {
    return locationList;
  }

  public void setLocationList(List<LocationApi> locationList) {
    this.locationList = locationList;
  }

  public Firm name(String name) {
    this.name = name;
    return this;
  }

   /**
   * 
   * @return name
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Firm vatId(String vatId) {
    this.vatId = vatId;
    return this;
  }

   /**
   * 
   * @return vatId
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getVatId() {
    return vatId;
  }

  public void setVatId(String vatId) {
    this.vatId = vatId;
  }

  public Firm nameAffix(String nameAffix) {
    this.nameAffix = nameAffix;
    return this;
  }

   /**
   * 
   * @return nameAffix
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getNameAffix() {
    return nameAffix;
  }

  public void setNameAffix(String nameAffix) {
    this.nameAffix = nameAffix;
  }

  public Firm id(String id) {
    this.id = id;
    return this;
  }

   /**
   * 
   * @return id
  **/
  @ApiModelProperty(example = "f4206901-c9b2-4e6e-8119-f7d623626060", value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Firm firm = (Firm) o;
    return Objects.equals(this.locationList, firm.locationList) &&
        Objects.equals(this.name, firm.name) &&
        Objects.equals(this.vatId, firm.vatId) &&
        Objects.equals(this.nameAffix, firm.nameAffix) &&
        Objects.equals(this.id, firm.id);
  }

  @Override
  public int hashCode() {
    return Objects.hash(locationList, name, vatId, nameAffix, id);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Firm {\n");
    
    sb.append("    locationList: ").append(toIndentedString(locationList)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    vatId: ").append(toIndentedString(vatId)).append("\n");
    sb.append("    nameAffix: ").append(toIndentedString(nameAffix)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

