/**
 * CPM API
 * Public API for CPM
 *
 * OpenAPI spec version: V1.0
 * Contact: info@addison.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package instantreports.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * FirmendatenGehaltsmodellApi
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2018-05-03T09:33:53.199+02:00")
public class FirmendatenGehaltsmodellApi   {
  @SerializedName("verguetungsdatenAktiv")
  private Boolean verguetungsdatenAktiv = null;

  @SerializedName("schnellErfassungLA")
  private Boolean schnellErfassungLA = null;

  @SerializedName("Gehalt")
  private Boolean gehalt = null;

  @SerializedName("VonBisErfassung")
  private Boolean vonBisErfassung = null;

  @SerializedName("showOldPendeldatenApp")
  private Boolean showOldPendeldatenApp = null;

  @SerializedName("Projekt")
  private Boolean projekt = null;

  @SerializedName("showNewPendeldatenApp")
  private Boolean showNewPendeldatenApp = null;

  @SerializedName("Sofortmeldungen")
  private Boolean sofortmeldungen = null;

  @SerializedName("wirtschaftsbereich")
  private Integer wirtschaftsbereich = null;

  @SerializedName("schnellErfassungES")
  private Boolean schnellErfassungES = null;

  @SerializedName("Lohn")
  private Boolean lohn = null;

  @SerializedName("vacationOverview")
  private Boolean vacationOverview = null;

  public FirmendatenGehaltsmodellApi verguetungsdatenAktiv(Boolean verguetungsdatenAktiv) {
    this.verguetungsdatenAktiv = verguetungsdatenAktiv;
    return this;
  }

   /**
   * 
   * @return verguetungsdatenAktiv
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Boolean getVerguetungsdatenAktiv() {
    return verguetungsdatenAktiv;
  }

  public void setVerguetungsdatenAktiv(Boolean verguetungsdatenAktiv) {
    this.verguetungsdatenAktiv = verguetungsdatenAktiv;
  }

  public FirmendatenGehaltsmodellApi schnellErfassungLA(Boolean schnellErfassungLA) {
    this.schnellErfassungLA = schnellErfassungLA;
    return this;
  }

   /**
   * 
   * @return schnellErfassungLA
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Boolean getSchnellErfassungLA() {
    return schnellErfassungLA;
  }

  public void setSchnellErfassungLA(Boolean schnellErfassungLA) {
    this.schnellErfassungLA = schnellErfassungLA;
  }

  public FirmendatenGehaltsmodellApi gehalt(Boolean gehalt) {
    this.gehalt = gehalt;
    return this;
  }

   /**
   * 
   * @return gehalt
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Boolean getGehalt() {
    return gehalt;
  }

  public void setGehalt(Boolean gehalt) {
    this.gehalt = gehalt;
  }

  public FirmendatenGehaltsmodellApi vonBisErfassung(Boolean vonBisErfassung) {
    this.vonBisErfassung = vonBisErfassung;
    return this;
  }

   /**
   * 
   * @return vonBisErfassung
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Boolean getVonBisErfassung() {
    return vonBisErfassung;
  }

  public void setVonBisErfassung(Boolean vonBisErfassung) {
    this.vonBisErfassung = vonBisErfassung;
  }

  public FirmendatenGehaltsmodellApi showOldPendeldatenApp(Boolean showOldPendeldatenApp) {
    this.showOldPendeldatenApp = showOldPendeldatenApp;
    return this;
  }

   /**
   * 
   * @return showOldPendeldatenApp
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Boolean getShowOldPendeldatenApp() {
    return showOldPendeldatenApp;
  }

  public void setShowOldPendeldatenApp(Boolean showOldPendeldatenApp) {
    this.showOldPendeldatenApp = showOldPendeldatenApp;
  }

  public FirmendatenGehaltsmodellApi projekt(Boolean projekt) {
    this.projekt = projekt;
    return this;
  }

   /**
   * 
   * @return projekt
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Boolean getProjekt() {
    return projekt;
  }

  public void setProjekt(Boolean projekt) {
    this.projekt = projekt;
  }

  public FirmendatenGehaltsmodellApi showNewPendeldatenApp(Boolean showNewPendeldatenApp) {
    this.showNewPendeldatenApp = showNewPendeldatenApp;
    return this;
  }

   /**
   * 
   * @return showNewPendeldatenApp
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Boolean getShowNewPendeldatenApp() {
    return showNewPendeldatenApp;
  }

  public void setShowNewPendeldatenApp(Boolean showNewPendeldatenApp) {
    this.showNewPendeldatenApp = showNewPendeldatenApp;
  }

  public FirmendatenGehaltsmodellApi sofortmeldungen(Boolean sofortmeldungen) {
    this.sofortmeldungen = sofortmeldungen;
    return this;
  }

   /**
   * 
   * @return sofortmeldungen
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Boolean getSofortmeldungen() {
    return sofortmeldungen;
  }

  public void setSofortmeldungen(Boolean sofortmeldungen) {
    this.sofortmeldungen = sofortmeldungen;
  }

  public FirmendatenGehaltsmodellApi wirtschaftsbereich(Integer wirtschaftsbereich) {
    this.wirtschaftsbereich = wirtschaftsbereich;
    return this;
  }

   /**
   * 
   * @return wirtschaftsbereich
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Integer getWirtschaftsbereich() {
    return wirtschaftsbereich;
  }

  public void setWirtschaftsbereich(Integer wirtschaftsbereich) {
    this.wirtschaftsbereich = wirtschaftsbereich;
  }

  public FirmendatenGehaltsmodellApi schnellErfassungES(Boolean schnellErfassungES) {
    this.schnellErfassungES = schnellErfassungES;
    return this;
  }

   /**
   * 
   * @return schnellErfassungES
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Boolean getSchnellErfassungES() {
    return schnellErfassungES;
  }

  public void setSchnellErfassungES(Boolean schnellErfassungES) {
    this.schnellErfassungES = schnellErfassungES;
  }

  public FirmendatenGehaltsmodellApi lohn(Boolean lohn) {
    this.lohn = lohn;
    return this;
  }

   /**
   * 
   * @return lohn
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Boolean getLohn() {
    return lohn;
  }

  public void setLohn(Boolean lohn) {
    this.lohn = lohn;
  }

  public FirmendatenGehaltsmodellApi vacationOverview(Boolean vacationOverview) {
    this.vacationOverview = vacationOverview;
    return this;
  }

   /**
   * 
   * @return vacationOverview
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Boolean getVacationOverview() {
    return vacationOverview;
  }

  public void setVacationOverview(Boolean vacationOverview) {
    this.vacationOverview = vacationOverview;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FirmendatenGehaltsmodellApi firmendatenGehaltsmodellApi = (FirmendatenGehaltsmodellApi) o;
    return Objects.equals(this.verguetungsdatenAktiv, firmendatenGehaltsmodellApi.verguetungsdatenAktiv) &&
        Objects.equals(this.schnellErfassungLA, firmendatenGehaltsmodellApi.schnellErfassungLA) &&
        Objects.equals(this.gehalt, firmendatenGehaltsmodellApi.gehalt) &&
        Objects.equals(this.vonBisErfassung, firmendatenGehaltsmodellApi.vonBisErfassung) &&
        Objects.equals(this.showOldPendeldatenApp, firmendatenGehaltsmodellApi.showOldPendeldatenApp) &&
        Objects.equals(this.projekt, firmendatenGehaltsmodellApi.projekt) &&
        Objects.equals(this.showNewPendeldatenApp, firmendatenGehaltsmodellApi.showNewPendeldatenApp) &&
        Objects.equals(this.sofortmeldungen, firmendatenGehaltsmodellApi.sofortmeldungen) &&
        Objects.equals(this.wirtschaftsbereich, firmendatenGehaltsmodellApi.wirtschaftsbereich) &&
        Objects.equals(this.schnellErfassungES, firmendatenGehaltsmodellApi.schnellErfassungES) &&
        Objects.equals(this.lohn, firmendatenGehaltsmodellApi.lohn) &&
        Objects.equals(this.vacationOverview, firmendatenGehaltsmodellApi.vacationOverview);
  }

  @Override
  public int hashCode() {
    return Objects.hash(verguetungsdatenAktiv, schnellErfassungLA, gehalt, vonBisErfassung, showOldPendeldatenApp, projekt, showNewPendeldatenApp, sofortmeldungen, wirtschaftsbereich, schnellErfassungES, lohn, vacationOverview);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FirmendatenGehaltsmodellApi {\n");
    
    sb.append("    verguetungsdatenAktiv: ").append(toIndentedString(verguetungsdatenAktiv)).append("\n");
    sb.append("    schnellErfassungLA: ").append(toIndentedString(schnellErfassungLA)).append("\n");
    sb.append("    gehalt: ").append(toIndentedString(gehalt)).append("\n");
    sb.append("    vonBisErfassung: ").append(toIndentedString(vonBisErfassung)).append("\n");
    sb.append("    showOldPendeldatenApp: ").append(toIndentedString(showOldPendeldatenApp)).append("\n");
    sb.append("    projekt: ").append(toIndentedString(projekt)).append("\n");
    sb.append("    showNewPendeldatenApp: ").append(toIndentedString(showNewPendeldatenApp)).append("\n");
    sb.append("    sofortmeldungen: ").append(toIndentedString(sofortmeldungen)).append("\n");
    sb.append("    wirtschaftsbereich: ").append(toIndentedString(wirtschaftsbereich)).append("\n");
    sb.append("    schnellErfassungES: ").append(toIndentedString(schnellErfassungES)).append("\n");
    sb.append("    lohn: ").append(toIndentedString(lohn)).append("\n");
    sb.append("    vacationOverview: ").append(toIndentedString(vacationOverview)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

