/**
 * CPM API
 * Public API for CPM
 *
 * OpenAPI spec version: V1.0
 * Contact: info@addison.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package instantreports.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * KontoStammDataApi
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2018-05-03T09:33:53.199+02:00")
public class KontoStammDataApi   {
  @SerializedName("tel1")
  private String tel1 = null;

  @SerializedName("tel2")
  private String tel2 = null;

  @SerializedName("bilanzBereich")
  private String bilanzBereich = null;

  @SerializedName("nachName")
  private String nachName = null;

  @SerializedName("kontoNummer")
  private Long kontoNummer = null;

  @SerializedName("finanzKonto")
  private Boolean finanzKonto = null;

  @SerializedName("adressZeile3")
  private String adressZeile3 = null;

  @SerializedName("wjID")
  private String wjID = null;

  @SerializedName("land")
  private String land = null;

  @SerializedName("email")
  private String email = null;

  @SerializedName("kontoBezeichnung")
  private String kontoBezeichnung = null;

  @SerializedName("kontoArt")
  private String kontoArt = null;

  @SerializedName("opKonto")
  private Boolean opKonto = null;

  @SerializedName("bundesLand")
  private String bundesLand = null;

  @SerializedName("strasse")
  private String strasse = null;

  @SerializedName("kontoBezeichnungKurz")
  private String kontoBezeichnungKurz = null;

  @SerializedName("anrede")
  private String anrede = null;

  @SerializedName("kontoId")
  private String kontoId = null;

  @SerializedName("vorName")
  private String vorName = null;

  @SerializedName("ort")
  private String ort = null;

  @SerializedName("branche")
  private String branche = null;

  @SerializedName("steuerKonto")
  private Boolean steuerKonto = null;

  @SerializedName("kontoTyp")
  private String kontoTyp = null;

  @SerializedName("mischKonto")
  private Boolean mischKonto = null;

  @SerializedName("plz")
  private String plz = null;

  public KontoStammDataApi tel1(String tel1) {
    this.tel1 = tel1;
    return this;
  }

   /**
   * 
   * @return tel1
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getTel1() {
    return tel1;
  }

  public void setTel1(String tel1) {
    this.tel1 = tel1;
  }

  public KontoStammDataApi tel2(String tel2) {
    this.tel2 = tel2;
    return this;
  }

   /**
   * 
   * @return tel2
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getTel2() {
    return tel2;
  }

  public void setTel2(String tel2) {
    this.tel2 = tel2;
  }

  public KontoStammDataApi bilanzBereich(String bilanzBereich) {
    this.bilanzBereich = bilanzBereich;
    return this;
  }

   /**
   * 
   * @return bilanzBereich
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getBilanzBereich() {
    return bilanzBereich;
  }

  public void setBilanzBereich(String bilanzBereich) {
    this.bilanzBereich = bilanzBereich;
  }

  public KontoStammDataApi nachName(String nachName) {
    this.nachName = nachName;
    return this;
  }

   /**
   * 
   * @return nachName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getNachName() {
    return nachName;
  }

  public void setNachName(String nachName) {
    this.nachName = nachName;
  }

  public KontoStammDataApi kontoNummer(Long kontoNummer) {
    this.kontoNummer = kontoNummer;
    return this;
  }

   /**
   *  (filterable/sortable)
   * @return kontoNummer
  **/
  @ApiModelProperty(example = "null", required = true, value = " (filterable/sortable)")
  public Long getKontoNummer() {
    return kontoNummer;
  }

  public void setKontoNummer(Long kontoNummer) {
    this.kontoNummer = kontoNummer;
  }

  public KontoStammDataApi finanzKonto(Boolean finanzKonto) {
    this.finanzKonto = finanzKonto;
    return this;
  }

   /**
   * 
   * @return finanzKonto
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getFinanzKonto() {
    return finanzKonto;
  }

  public void setFinanzKonto(Boolean finanzKonto) {
    this.finanzKonto = finanzKonto;
  }

  public KontoStammDataApi adressZeile3(String adressZeile3) {
    this.adressZeile3 = adressZeile3;
    return this;
  }

   /**
   * 
   * @return adressZeile3
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getAdressZeile3() {
    return adressZeile3;
  }

  public void setAdressZeile3(String adressZeile3) {
    this.adressZeile3 = adressZeile3;
  }

  public KontoStammDataApi wjID(String wjID) {
    this.wjID = wjID;
    return this;
  }

   /**
   * 
   * @return wjID
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getWjID() {
    return wjID;
  }

  public void setWjID(String wjID) {
    this.wjID = wjID;
  }

  public KontoStammDataApi land(String land) {
    this.land = land;
    return this;
  }

   /**
   * 
   * @return land
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getLand() {
    return land;
  }

  public void setLand(String land) {
    this.land = land;
  }

  public KontoStammDataApi email(String email) {
    this.email = email;
    return this;
  }

   /**
   * 
   * @return email
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public KontoStammDataApi kontoBezeichnung(String kontoBezeichnung) {
    this.kontoBezeichnung = kontoBezeichnung;
    return this;
  }

   /**
   *  (filterable/sortable)
   * @return kontoBezeichnung
  **/
  @ApiModelProperty(example = "null", required = true, value = " (filterable/sortable)")
  public String getKontoBezeichnung() {
    return kontoBezeichnung;
  }

  public void setKontoBezeichnung(String kontoBezeichnung) {
    this.kontoBezeichnung = kontoBezeichnung;
  }

  public KontoStammDataApi kontoArt(String kontoArt) {
    this.kontoArt = kontoArt;
    return this;
  }

   /**
   * 
   * @return kontoArt
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getKontoArt() {
    return kontoArt;
  }

  public void setKontoArt(String kontoArt) {
    this.kontoArt = kontoArt;
  }

  public KontoStammDataApi opKonto(Boolean opKonto) {
    this.opKonto = opKonto;
    return this;
  }

   /**
   * 
   * @return opKonto
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getOpKonto() {
    return opKonto;
  }

  public void setOpKonto(Boolean opKonto) {
    this.opKonto = opKonto;
  }

  public KontoStammDataApi bundesLand(String bundesLand) {
    this.bundesLand = bundesLand;
    return this;
  }

   /**
   * 
   * @return bundesLand
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getBundesLand() {
    return bundesLand;
  }

  public void setBundesLand(String bundesLand) {
    this.bundesLand = bundesLand;
  }

  public KontoStammDataApi strasse(String strasse) {
    this.strasse = strasse;
    return this;
  }

   /**
   * 
   * @return strasse
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getStrasse() {
    return strasse;
  }

  public void setStrasse(String strasse) {
    this.strasse = strasse;
  }

  public KontoStammDataApi kontoBezeichnungKurz(String kontoBezeichnungKurz) {
    this.kontoBezeichnungKurz = kontoBezeichnungKurz;
    return this;
  }

   /**
   *  (filterable/sortable)
   * @return kontoBezeichnungKurz
  **/
  @ApiModelProperty(example = "null", required = true, value = " (filterable/sortable)")
  public String getKontoBezeichnungKurz() {
    return kontoBezeichnungKurz;
  }

  public void setKontoBezeichnungKurz(String kontoBezeichnungKurz) {
    this.kontoBezeichnungKurz = kontoBezeichnungKurz;
  }

  public KontoStammDataApi anrede(String anrede) {
    this.anrede = anrede;
    return this;
  }

   /**
   * 
   * @return anrede
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getAnrede() {
    return anrede;
  }

  public void setAnrede(String anrede) {
    this.anrede = anrede;
  }

  public KontoStammDataApi kontoId(String kontoId) {
    this.kontoId = kontoId;
    return this;
  }

   /**
   * 
   * @return kontoId
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getKontoId() {
    return kontoId;
  }

  public void setKontoId(String kontoId) {
    this.kontoId = kontoId;
  }

  public KontoStammDataApi vorName(String vorName) {
    this.vorName = vorName;
    return this;
  }

   /**
   * 
   * @return vorName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getVorName() {
    return vorName;
  }

  public void setVorName(String vorName) {
    this.vorName = vorName;
  }

  public KontoStammDataApi ort(String ort) {
    this.ort = ort;
    return this;
  }

   /**
   * 
   * @return ort
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getOrt() {
    return ort;
  }

  public void setOrt(String ort) {
    this.ort = ort;
  }

  public KontoStammDataApi branche(String branche) {
    this.branche = branche;
    return this;
  }

   /**
   * 
   * @return branche
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getBranche() {
    return branche;
  }

  public void setBranche(String branche) {
    this.branche = branche;
  }

  public KontoStammDataApi steuerKonto(Boolean steuerKonto) {
    this.steuerKonto = steuerKonto;
    return this;
  }

   /**
   * 
   * @return steuerKonto
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getSteuerKonto() {
    return steuerKonto;
  }

  public void setSteuerKonto(Boolean steuerKonto) {
    this.steuerKonto = steuerKonto;
  }

  public KontoStammDataApi kontoTyp(String kontoTyp) {
    this.kontoTyp = kontoTyp;
    return this;
  }

   /**
   * 
   * @return kontoTyp
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getKontoTyp() {
    return kontoTyp;
  }

  public void setKontoTyp(String kontoTyp) {
    this.kontoTyp = kontoTyp;
  }

  public KontoStammDataApi mischKonto(Boolean mischKonto) {
    this.mischKonto = mischKonto;
    return this;
  }

   /**
   * 
   * @return mischKonto
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getMischKonto() {
    return mischKonto;
  }

  public void setMischKonto(Boolean mischKonto) {
    this.mischKonto = mischKonto;
  }

  public KontoStammDataApi plz(String plz) {
    this.plz = plz;
    return this;
  }

   /**
   * 
   * @return plz
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getPlz() {
    return plz;
  }

  public void setPlz(String plz) {
    this.plz = plz;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    KontoStammDataApi kontoStammDataApi = (KontoStammDataApi) o;
    return Objects.equals(this.tel1, kontoStammDataApi.tel1) &&
        Objects.equals(this.tel2, kontoStammDataApi.tel2) &&
        Objects.equals(this.bilanzBereich, kontoStammDataApi.bilanzBereich) &&
        Objects.equals(this.nachName, kontoStammDataApi.nachName) &&
        Objects.equals(this.kontoNummer, kontoStammDataApi.kontoNummer) &&
        Objects.equals(this.finanzKonto, kontoStammDataApi.finanzKonto) &&
        Objects.equals(this.adressZeile3, kontoStammDataApi.adressZeile3) &&
        Objects.equals(this.wjID, kontoStammDataApi.wjID) &&
        Objects.equals(this.land, kontoStammDataApi.land) &&
        Objects.equals(this.email, kontoStammDataApi.email) &&
        Objects.equals(this.kontoBezeichnung, kontoStammDataApi.kontoBezeichnung) &&
        Objects.equals(this.kontoArt, kontoStammDataApi.kontoArt) &&
        Objects.equals(this.opKonto, kontoStammDataApi.opKonto) &&
        Objects.equals(this.bundesLand, kontoStammDataApi.bundesLand) &&
        Objects.equals(this.strasse, kontoStammDataApi.strasse) &&
        Objects.equals(this.kontoBezeichnungKurz, kontoStammDataApi.kontoBezeichnungKurz) &&
        Objects.equals(this.anrede, kontoStammDataApi.anrede) &&
        Objects.equals(this.kontoId, kontoStammDataApi.kontoId) &&
        Objects.equals(this.vorName, kontoStammDataApi.vorName) &&
        Objects.equals(this.ort, kontoStammDataApi.ort) &&
        Objects.equals(this.branche, kontoStammDataApi.branche) &&
        Objects.equals(this.steuerKonto, kontoStammDataApi.steuerKonto) &&
        Objects.equals(this.kontoTyp, kontoStammDataApi.kontoTyp) &&
        Objects.equals(this.mischKonto, kontoStammDataApi.mischKonto) &&
        Objects.equals(this.plz, kontoStammDataApi.plz);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tel1, tel2, bilanzBereich, nachName, kontoNummer, finanzKonto, adressZeile3, wjID, land, email, kontoBezeichnung, kontoArt, opKonto, bundesLand, strasse, kontoBezeichnungKurz, anrede, kontoId, vorName, ort, branche, steuerKonto, kontoTyp, mischKonto, plz);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class KontoStammDataApi {\n");
    
    sb.append("    tel1: ").append(toIndentedString(tel1)).append("\n");
    sb.append("    tel2: ").append(toIndentedString(tel2)).append("\n");
    sb.append("    bilanzBereich: ").append(toIndentedString(bilanzBereich)).append("\n");
    sb.append("    nachName: ").append(toIndentedString(nachName)).append("\n");
    sb.append("    kontoNummer: ").append(toIndentedString(kontoNummer)).append("\n");
    sb.append("    finanzKonto: ").append(toIndentedString(finanzKonto)).append("\n");
    sb.append("    adressZeile3: ").append(toIndentedString(adressZeile3)).append("\n");
    sb.append("    wjID: ").append(toIndentedString(wjID)).append("\n");
    sb.append("    land: ").append(toIndentedString(land)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    kontoBezeichnung: ").append(toIndentedString(kontoBezeichnung)).append("\n");
    sb.append("    kontoArt: ").append(toIndentedString(kontoArt)).append("\n");
    sb.append("    opKonto: ").append(toIndentedString(opKonto)).append("\n");
    sb.append("    bundesLand: ").append(toIndentedString(bundesLand)).append("\n");
    sb.append("    strasse: ").append(toIndentedString(strasse)).append("\n");
    sb.append("    kontoBezeichnungKurz: ").append(toIndentedString(kontoBezeichnungKurz)).append("\n");
    sb.append("    anrede: ").append(toIndentedString(anrede)).append("\n");
    sb.append("    kontoId: ").append(toIndentedString(kontoId)).append("\n");
    sb.append("    vorName: ").append(toIndentedString(vorName)).append("\n");
    sb.append("    ort: ").append(toIndentedString(ort)).append("\n");
    sb.append("    branche: ").append(toIndentedString(branche)).append("\n");
    sb.append("    steuerKonto: ").append(toIndentedString(steuerKonto)).append("\n");
    sb.append("    kontoTyp: ").append(toIndentedString(kontoTyp)).append("\n");
    sb.append("    mischKonto: ").append(toIndentedString(mischKonto)).append("\n");
    sb.append("    plz: ").append(toIndentedString(plz)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

