/**
 * CPM API
 * Public API for CPM
 *
 * OpenAPI spec version: V1.0
 * Contact: info@addison.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package instantreports.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * LohnartenplanDefinitionApi
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2018-05-03T09:33:53.199+02:00")
public class LohnartenplanDefinitionApi   {
  @SerializedName("bezeichnung")
  private String bezeichnung = null;

  @SerializedName("letztesImportdatum")
  private String letztesImportdatum = null;

  @SerializedName("nummer")
  private String nummer = null;

  public LohnartenplanDefinitionApi bezeichnung(String bezeichnung) {
    this.bezeichnung = bezeichnung;
    return this;
  }

   /**
   *  (filterable/sortable)
   * @return bezeichnung
  **/
  @ApiModelProperty(example = "null", required = true, value = " (filterable/sortable)")
  public String getBezeichnung() {
    return bezeichnung;
  }

  public void setBezeichnung(String bezeichnung) {
    this.bezeichnung = bezeichnung;
  }

  public LohnartenplanDefinitionApi letztesImportdatum(String letztesImportdatum) {
    this.letztesImportdatum = letztesImportdatum;
    return this;
  }

   /**
   * 
   * @return letztesImportdatum
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getLetztesImportdatum() {
    return letztesImportdatum;
  }

  public void setLetztesImportdatum(String letztesImportdatum) {
    this.letztesImportdatum = letztesImportdatum;
  }

  public LohnartenplanDefinitionApi nummer(String nummer) {
    this.nummer = nummer;
    return this;
  }

   /**
   *  (filterable/sortable)
   * @return nummer
  **/
  @ApiModelProperty(example = "null", required = true, value = " (filterable/sortable)")
  public String getNummer() {
    return nummer;
  }

  public void setNummer(String nummer) {
    this.nummer = nummer;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LohnartenplanDefinitionApi lohnartenplanDefinitionApi = (LohnartenplanDefinitionApi) o;
    return Objects.equals(this.bezeichnung, lohnartenplanDefinitionApi.bezeichnung) &&
        Objects.equals(this.letztesImportdatum, lohnartenplanDefinitionApi.letztesImportdatum) &&
        Objects.equals(this.nummer, lohnartenplanDefinitionApi.nummer);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bezeichnung, letztesImportdatum, nummer);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LohnartenplanDefinitionApi {\n");
    
    sb.append("    bezeichnung: ").append(toIndentedString(bezeichnung)).append("\n");
    sb.append("    letztesImportdatum: ").append(toIndentedString(letztesImportdatum)).append("\n");
    sb.append("    nummer: ").append(toIndentedString(nummer)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

