/**
 * CPM API
 * Public API for CPM
 *
 * OpenAPI spec version: V1.0
 * Contact: info@addison.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package instantreports.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.LocalDate;


/**
 * Meldungendata
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2018-05-03T09:33:53.199+02:00")
public class Meldungendata   {
  @SerializedName("verarbeitungsdatum")
  private LocalDate verarbeitungsdatum = null;

  @SerializedName("empfangsdatumADS")
  private LocalDate empfangsdatumADS = null;

  @SerializedName("organisationid")
  private String organisationid = null;

  @SerializedName("sendedatum")
  private LocalDate sendedatum = null;

  @SerializedName("mandantennummer")
  private String mandantennummer = null;

  @SerializedName("betrag")
  private Long betrag = null;

  @SerializedName("identifikationArbeitnehemr")
  private String identifikationArbeitnehemr = null;

  @SerializedName("fehlertext")
  private String fehlertext = null;

  @SerializedName("messageID")
  private String messageID = null;

  @SerializedName("bereitstellungsdatum")
  private LocalDate bereitstellungsdatum = null;

  @SerializedName("empfaenger")
  private String empfaenger = null;

  @SerializedName("zeitraumBis")
  private LocalDate zeitraumBis = null;

  @SerializedName("stornokennzeichen")
  private String stornokennzeichen = null;

  @SerializedName("sendedatumADS")
  private LocalDate sendedatumADS = null;

  @SerializedName("meldedaten")
  private String meldedaten = null;

  @SerializedName("arbeitnehmernummer")
  private String arbeitnehmernummer = null;

  @SerializedName("contractId")
  private String contractId = null;

  @SerializedName("zeitraumVon")
  private LocalDate zeitraumVon = null;

  @SerializedName("sendestatus")
  private String sendestatus = null;

  @SerializedName("empfangsdatum")
  private LocalDate empfangsdatum = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("abgabegrund")
  private String abgabegrund = null;

  public Meldungendata verarbeitungsdatum(LocalDate verarbeitungsdatum) {
    this.verarbeitungsdatum = verarbeitungsdatum;
    return this;
  }

   /**
   *  (filterable/sortable)
   * @return verarbeitungsdatum
  **/
  @ApiModelProperty(example = "null", required = true, value = " (filterable/sortable)")
  public LocalDate getVerarbeitungsdatum() {
    return verarbeitungsdatum;
  }

  public void setVerarbeitungsdatum(LocalDate verarbeitungsdatum) {
    this.verarbeitungsdatum = verarbeitungsdatum;
  }

  public Meldungendata empfangsdatumADS(LocalDate empfangsdatumADS) {
    this.empfangsdatumADS = empfangsdatumADS;
    return this;
  }

   /**
   *  (filterable/sortable)
   * @return empfangsdatumADS
  **/
  @ApiModelProperty(example = "null", required = true, value = " (filterable/sortable)")
  public LocalDate getEmpfangsdatumADS() {
    return empfangsdatumADS;
  }

  public void setEmpfangsdatumADS(LocalDate empfangsdatumADS) {
    this.empfangsdatumADS = empfangsdatumADS;
  }

  public Meldungendata organisationid(String organisationid) {
    this.organisationid = organisationid;
    return this;
  }

   /**
   *  (filterable/sortable)
   * @return organisationid
  **/
  @ApiModelProperty(example = "null", required = true, value = " (filterable/sortable)")
  public String getOrganisationid() {
    return organisationid;
  }

  public void setOrganisationid(String organisationid) {
    this.organisationid = organisationid;
  }

  public Meldungendata sendedatum(LocalDate sendedatum) {
    this.sendedatum = sendedatum;
    return this;
  }

   /**
   *  (filterable/sortable)
   * @return sendedatum
  **/
  @ApiModelProperty(example = "null", required = true, value = " (filterable/sortable)")
  public LocalDate getSendedatum() {
    return sendedatum;
  }

  public void setSendedatum(LocalDate sendedatum) {
    this.sendedatum = sendedatum;
  }

  public Meldungendata mandantennummer(String mandantennummer) {
    this.mandantennummer = mandantennummer;
    return this;
  }

   /**
   *  (filterable/sortable)
   * @return mandantennummer
  **/
  @ApiModelProperty(example = "null", required = true, value = " (filterable/sortable)")
  public String getMandantennummer() {
    return mandantennummer;
  }

  public void setMandantennummer(String mandantennummer) {
    this.mandantennummer = mandantennummer;
  }

  public Meldungendata betrag(Long betrag) {
    this.betrag = betrag;
    return this;
  }

   /**
   *  (filterable/sortable)
   * @return betrag
  **/
  @ApiModelProperty(example = "null", required = true, value = " (filterable/sortable)")
  public Long getBetrag() {
    return betrag;
  }

  public void setBetrag(Long betrag) {
    this.betrag = betrag;
  }

  public Meldungendata identifikationArbeitnehemr(String identifikationArbeitnehemr) {
    this.identifikationArbeitnehemr = identifikationArbeitnehemr;
    return this;
  }

   /**
   *  (filterable/sortable)
   * @return identifikationArbeitnehemr
  **/
  @ApiModelProperty(example = "null", required = true, value = " (filterable/sortable)")
  public String getIdentifikationArbeitnehemr() {
    return identifikationArbeitnehemr;
  }

  public void setIdentifikationArbeitnehemr(String identifikationArbeitnehemr) {
    this.identifikationArbeitnehemr = identifikationArbeitnehemr;
  }

  public Meldungendata fehlertext(String fehlertext) {
    this.fehlertext = fehlertext;
    return this;
  }

   /**
   *  (filterable/sortable)
   * @return fehlertext
  **/
  @ApiModelProperty(example = "null", required = true, value = " (filterable/sortable)")
  public String getFehlertext() {
    return fehlertext;
  }

  public void setFehlertext(String fehlertext) {
    this.fehlertext = fehlertext;
  }

  public Meldungendata messageID(String messageID) {
    this.messageID = messageID;
    return this;
  }

   /**
   *  (filterable/sortable)
   * @return messageID
  **/
  @ApiModelProperty(example = "null", required = true, value = " (filterable/sortable)")
  public String getMessageID() {
    return messageID;
  }

  public void setMessageID(String messageID) {
    this.messageID = messageID;
  }

  public Meldungendata bereitstellungsdatum(LocalDate bereitstellungsdatum) {
    this.bereitstellungsdatum = bereitstellungsdatum;
    return this;
  }

   /**
   *  (filterable/sortable)
   * @return bereitstellungsdatum
  **/
  @ApiModelProperty(example = "null", required = true, value = " (filterable/sortable)")
  public LocalDate getBereitstellungsdatum() {
    return bereitstellungsdatum;
  }

  public void setBereitstellungsdatum(LocalDate bereitstellungsdatum) {
    this.bereitstellungsdatum = bereitstellungsdatum;
  }

  public Meldungendata empfaenger(String empfaenger) {
    this.empfaenger = empfaenger;
    return this;
  }

   /**
   *  (filterable/sortable)
   * @return empfaenger
  **/
  @ApiModelProperty(example = "null", required = true, value = " (filterable/sortable)")
  public String getEmpfaenger() {
    return empfaenger;
  }

  public void setEmpfaenger(String empfaenger) {
    this.empfaenger = empfaenger;
  }

  public Meldungendata zeitraumBis(LocalDate zeitraumBis) {
    this.zeitraumBis = zeitraumBis;
    return this;
  }

   /**
   *  (filterable/sortable)
   * @return zeitraumBis
  **/
  @ApiModelProperty(example = "null", required = true, value = " (filterable/sortable)")
  public LocalDate getZeitraumBis() {
    return zeitraumBis;
  }

  public void setZeitraumBis(LocalDate zeitraumBis) {
    this.zeitraumBis = zeitraumBis;
  }

  public Meldungendata stornokennzeichen(String stornokennzeichen) {
    this.stornokennzeichen = stornokennzeichen;
    return this;
  }

   /**
   *  (filterable/sortable)
   * @return stornokennzeichen
  **/
  @ApiModelProperty(example = "null", required = true, value = " (filterable/sortable)")
  public String getStornokennzeichen() {
    return stornokennzeichen;
  }

  public void setStornokennzeichen(String stornokennzeichen) {
    this.stornokennzeichen = stornokennzeichen;
  }

  public Meldungendata sendedatumADS(LocalDate sendedatumADS) {
    this.sendedatumADS = sendedatumADS;
    return this;
  }

   /**
   *  (filterable/sortable)
   * @return sendedatumADS
  **/
  @ApiModelProperty(example = "null", required = true, value = " (filterable/sortable)")
  public LocalDate getSendedatumADS() {
    return sendedatumADS;
  }

  public void setSendedatumADS(LocalDate sendedatumADS) {
    this.sendedatumADS = sendedatumADS;
  }

  public Meldungendata meldedaten(String meldedaten) {
    this.meldedaten = meldedaten;
    return this;
  }

   /**
   *  (filterable/sortable)
   * @return meldedaten
  **/
  @ApiModelProperty(example = "null", required = true, value = " (filterable/sortable)")
  public String getMeldedaten() {
    return meldedaten;
  }

  public void setMeldedaten(String meldedaten) {
    this.meldedaten = meldedaten;
  }

  public Meldungendata arbeitnehmernummer(String arbeitnehmernummer) {
    this.arbeitnehmernummer = arbeitnehmernummer;
    return this;
  }

   /**
   *  (filterable/sortable)
   * @return arbeitnehmernummer
  **/
  @ApiModelProperty(example = "null", required = true, value = " (filterable/sortable)")
  public String getArbeitnehmernummer() {
    return arbeitnehmernummer;
  }

  public void setArbeitnehmernummer(String arbeitnehmernummer) {
    this.arbeitnehmernummer = arbeitnehmernummer;
  }

  public Meldungendata contractId(String contractId) {
    this.contractId = contractId;
    return this;
  }

   /**
   *  (filterable/sortable)
   * @return contractId
  **/
  @ApiModelProperty(example = "null", required = true, value = " (filterable/sortable)")
  public String getContractId() {
    return contractId;
  }

  public void setContractId(String contractId) {
    this.contractId = contractId;
  }

  public Meldungendata zeitraumVon(LocalDate zeitraumVon) {
    this.zeitraumVon = zeitraumVon;
    return this;
  }

   /**
   *  (filterable/sortable)
   * @return zeitraumVon
  **/
  @ApiModelProperty(example = "null", required = true, value = " (filterable/sortable)")
  public LocalDate getZeitraumVon() {
    return zeitraumVon;
  }

  public void setZeitraumVon(LocalDate zeitraumVon) {
    this.zeitraumVon = zeitraumVon;
  }

  public Meldungendata sendestatus(String sendestatus) {
    this.sendestatus = sendestatus;
    return this;
  }

   /**
   *  (filterable/sortable)
   * @return sendestatus
  **/
  @ApiModelProperty(example = "null", required = true, value = " (filterable/sortable)")
  public String getSendestatus() {
    return sendestatus;
  }

  public void setSendestatus(String sendestatus) {
    this.sendestatus = sendestatus;
  }

  public Meldungendata empfangsdatum(LocalDate empfangsdatum) {
    this.empfangsdatum = empfangsdatum;
    return this;
  }

   /**
   *  (filterable/sortable)
   * @return empfangsdatum
  **/
  @ApiModelProperty(example = "null", required = true, value = " (filterable/sortable)")
  public LocalDate getEmpfangsdatum() {
    return empfangsdatum;
  }

  public void setEmpfangsdatum(LocalDate empfangsdatum) {
    this.empfangsdatum = empfangsdatum;
  }

  public Meldungendata id(String id) {
    this.id = id;
    return this;
  }

   /**
   * 
   * @return id
  **/
  @ApiModelProperty(example = "f4206901-c9b2-4e6e-8119-f7d623626060", value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Meldungendata abgabegrund(String abgabegrund) {
    this.abgabegrund = abgabegrund;
    return this;
  }

   /**
   *  (filterable/sortable)
   * @return abgabegrund
  **/
  @ApiModelProperty(example = "null", required = true, value = " (filterable/sortable)")
  public String getAbgabegrund() {
    return abgabegrund;
  }

  public void setAbgabegrund(String abgabegrund) {
    this.abgabegrund = abgabegrund;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Meldungendata meldungendata = (Meldungendata) o;
    return Objects.equals(this.verarbeitungsdatum, meldungendata.verarbeitungsdatum) &&
        Objects.equals(this.empfangsdatumADS, meldungendata.empfangsdatumADS) &&
        Objects.equals(this.organisationid, meldungendata.organisationid) &&
        Objects.equals(this.sendedatum, meldungendata.sendedatum) &&
        Objects.equals(this.mandantennummer, meldungendata.mandantennummer) &&
        Objects.equals(this.betrag, meldungendata.betrag) &&
        Objects.equals(this.identifikationArbeitnehemr, meldungendata.identifikationArbeitnehemr) &&
        Objects.equals(this.fehlertext, meldungendata.fehlertext) &&
        Objects.equals(this.messageID, meldungendata.messageID) &&
        Objects.equals(this.bereitstellungsdatum, meldungendata.bereitstellungsdatum) &&
        Objects.equals(this.empfaenger, meldungendata.empfaenger) &&
        Objects.equals(this.zeitraumBis, meldungendata.zeitraumBis) &&
        Objects.equals(this.stornokennzeichen, meldungendata.stornokennzeichen) &&
        Objects.equals(this.sendedatumADS, meldungendata.sendedatumADS) &&
        Objects.equals(this.meldedaten, meldungendata.meldedaten) &&
        Objects.equals(this.arbeitnehmernummer, meldungendata.arbeitnehmernummer) &&
        Objects.equals(this.contractId, meldungendata.contractId) &&
        Objects.equals(this.zeitraumVon, meldungendata.zeitraumVon) &&
        Objects.equals(this.sendestatus, meldungendata.sendestatus) &&
        Objects.equals(this.empfangsdatum, meldungendata.empfangsdatum) &&
        Objects.equals(this.id, meldungendata.id) &&
        Objects.equals(this.abgabegrund, meldungendata.abgabegrund);
  }

  @Override
  public int hashCode() {
    return Objects.hash(verarbeitungsdatum, empfangsdatumADS, organisationid, sendedatum, mandantennummer, betrag, identifikationArbeitnehemr, fehlertext, messageID, bereitstellungsdatum, empfaenger, zeitraumBis, stornokennzeichen, sendedatumADS, meldedaten, arbeitnehmernummer, contractId, zeitraumVon, sendestatus, empfangsdatum, id, abgabegrund);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Meldungendata {\n");
    
    sb.append("    verarbeitungsdatum: ").append(toIndentedString(verarbeitungsdatum)).append("\n");
    sb.append("    empfangsdatumADS: ").append(toIndentedString(empfangsdatumADS)).append("\n");
    sb.append("    organisationid: ").append(toIndentedString(organisationid)).append("\n");
    sb.append("    sendedatum: ").append(toIndentedString(sendedatum)).append("\n");
    sb.append("    mandantennummer: ").append(toIndentedString(mandantennummer)).append("\n");
    sb.append("    betrag: ").append(toIndentedString(betrag)).append("\n");
    sb.append("    identifikationArbeitnehemr: ").append(toIndentedString(identifikationArbeitnehemr)).append("\n");
    sb.append("    fehlertext: ").append(toIndentedString(fehlertext)).append("\n");
    sb.append("    messageID: ").append(toIndentedString(messageID)).append("\n");
    sb.append("    bereitstellungsdatum: ").append(toIndentedString(bereitstellungsdatum)).append("\n");
    sb.append("    empfaenger: ").append(toIndentedString(empfaenger)).append("\n");
    sb.append("    zeitraumBis: ").append(toIndentedString(zeitraumBis)).append("\n");
    sb.append("    stornokennzeichen: ").append(toIndentedString(stornokennzeichen)).append("\n");
    sb.append("    sendedatumADS: ").append(toIndentedString(sendedatumADS)).append("\n");
    sb.append("    meldedaten: ").append(toIndentedString(meldedaten)).append("\n");
    sb.append("    arbeitnehmernummer: ").append(toIndentedString(arbeitnehmernummer)).append("\n");
    sb.append("    contractId: ").append(toIndentedString(contractId)).append("\n");
    sb.append("    zeitraumVon: ").append(toIndentedString(zeitraumVon)).append("\n");
    sb.append("    sendestatus: ").append(toIndentedString(sendestatus)).append("\n");
    sb.append("    empfangsdatum: ").append(toIndentedString(empfangsdatum)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    abgabegrund: ").append(toIndentedString(abgabegrund)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

