/**
 * CPM API
 * Public API for CPM
 *
 * OpenAPI spec version: V1.0
 * Contact: info@addison.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package instantreports.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import instantreports.model.GroupAccessApi;
import instantreports.model.OrganizationIDAccessApi;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;


/**
 * Member
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2018-05-03T09:33:53.199+02:00")
public class Member   {
  @SerializedName("organisationId")
  private String organisationId = null;

  @SerializedName("portalMemberType")
  private String portalMemberType = null;

  @SerializedName("orga")
  private String orga = null;

  @SerializedName("active")
  private Boolean active = null;

  @SerializedName("parentId")
  private String parentId = null;

  @SerializedName("administrator")
  private Boolean administrator = null;

  @SerializedName("loginName")
  private String loginName = null;

  @SerializedName("legacyMember")
  private Boolean legacyMember = null;

  @SerializedName("portalId")
  private String portalId = null;

  @SerializedName("restrictedToOrganizations")
  private Boolean restrictedToOrganizations = null;

  @SerializedName("groupAccessList")
  private List<GroupAccessApi> groupAccessList = new ArrayList<GroupAccessApi>();

  @SerializedName("tenantId")
  private String tenantId = null;

  @SerializedName("legacyId")
  private String legacyId = null;

  @SerializedName("orgaWhiteList")
  private List<OrganizationIDAccessApi> orgaWhiteList = new ArrayList<OrganizationIDAccessApi>();

  @SerializedName("id")
  private String id = null;

  @SerializedName("name2")
  private String name2 = null;

  @SerializedName("name1")
  private String name1 = null;

  @SerializedName("memberRole")
  private Integer memberRole = null;

  @SerializedName("info")
  private String info = null;

  public Member organisationId(String organisationId) {
    this.organisationId = organisationId;
    return this;
  }

   /**
   * root organisation (filterable/sortable)
   * @return organisationId
  **/
  @ApiModelProperty(example = "10dc3872-9cb1-4733-bcab-1810af5469da", required = true, value = "root organisation (filterable/sortable)")
  public String getOrganisationId() {
    return organisationId;
  }

  public void setOrganisationId(String organisationId) {
    this.organisationId = organisationId;
  }

  public Member portalMemberType(String portalMemberType) {
    this.portalMemberType = portalMemberType;
    return this;
  }

   /**
   * portal member type
   * @return portalMemberType
  **/
  @ApiModelProperty(example = "null", value = "portal member type")
  public String getPortalMemberType() {
    return portalMemberType;
  }

  public void setPortalMemberType(String portalMemberType) {
    this.portalMemberType = portalMemberType;
  }

  public Member orga(String orga) {
    this.orga = orga;
    return this;
  }

   /**
   * client no (filterable/sortable)
   * @return orga
  **/
  @ApiModelProperty(example = "10000", required = true, value = "client no (filterable/sortable)")
  public String getOrga() {
    return orga;
  }

  public void setOrga(String orga) {
    this.orga = orga;
  }

  public Member active(Boolean active) {
    this.active = active;
    return this;
  }

   /**
   * active (filterable/sortable)
   * @return active
  **/
  @ApiModelProperty(example = "null", value = "active (filterable/sortable)")
  public Boolean getActive() {
    return active;
  }

  public void setActive(Boolean active) {
    this.active = active;
  }

  public Member parentId(String parentId) {
    this.parentId = parentId;
    return this;
  }

   /**
   * tax advisor (filterable/sortable)
   * @return parentId
  **/
  @ApiModelProperty(example = "10dc3872-9cb1-4733-bcab-1810af5469da", value = "tax advisor (filterable/sortable)")
  public String getParentId() {
    return parentId;
  }

  public void setParentId(String parentId) {
    this.parentId = parentId;
  }

  public Member administrator(Boolean administrator) {
    this.administrator = administrator;
    return this;
  }

   /**
   * admin (filterable/sortable)
   * @return administrator
  **/
  @ApiModelProperty(example = "false", value = "admin (filterable/sortable)")
  public Boolean getAdministrator() {
    return administrator;
  }

  public void setAdministrator(Boolean administrator) {
    this.administrator = administrator;
  }

  public Member loginName(String loginName) {
    this.loginName = loginName;
    return this;
  }

   /**
   * login name (filterable/sortable)
   * @return loginName
  **/
  @ApiModelProperty(example = "loginName", required = true, value = "login name (filterable/sortable)")
  public String getLoginName() {
    return loginName;
  }

  public void setLoginName(String loginName) {
    this.loginName = loginName;
  }

  public Member legacyMember(Boolean legacyMember) {
    this.legacyMember = legacyMember;
    return this;
  }

   /**
   * member of legacy application (filterable/sortable)
   * @return legacyMember
  **/
  @ApiModelProperty(example = "null", value = "member of legacy application (filterable/sortable)")
  public Boolean getLegacyMember() {
    return legacyMember;
  }

  public void setLegacyMember(Boolean legacyMember) {
    this.legacyMember = legacyMember;
  }

  public Member portalId(String portalId) {
    this.portalId = portalId;
    return this;
  }

   /**
   * online portal id (filterable/sortable)
   * @return portalId
  **/
  @ApiModelProperty(example = "00000000-0000-0000-0000-000000000000", value = "online portal id (filterable/sortable)")
  public String getPortalId() {
    return portalId;
  }

  public void setPortalId(String portalId) {
    this.portalId = portalId;
  }

  public Member restrictedToOrganizations(Boolean restrictedToOrganizations) {
    this.restrictedToOrganizations = restrictedToOrganizations;
    return this;
  }

   /**
   * restricted access to configured organizations only
   * @return restrictedToOrganizations
  **/
  @ApiModelProperty(example = "null", value = "restricted access to configured organizations only")
  public Boolean getRestrictedToOrganizations() {
    return restrictedToOrganizations;
  }

  public void setRestrictedToOrganizations(Boolean restrictedToOrganizations) {
    this.restrictedToOrganizations = restrictedToOrganizations;
  }

  public Member groupAccessList(List<GroupAccessApi> groupAccessList) {
    this.groupAccessList = groupAccessList;
    return this;
  }

  public Member addGroupAccessListItem(GroupAccessApi groupAccessListItem) {
    this.groupAccessList.add(groupAccessListItem);
    return this;
  }

   /**
   * Get groupAccessList
   * @return groupAccessList
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<GroupAccessApi> getGroupAccessList() {
    return groupAccessList;
  }

  public void setGroupAccessList(List<GroupAccessApi> groupAccessList) {
    this.groupAccessList = groupAccessList;
  }

  public Member tenantId(String tenantId) {
    this.tenantId = tenantId;
    return this;
  }

   /**
   * tenant id (filterable/sortable)
   * @return tenantId
  **/
  @ApiModelProperty(example = "10dc3872-9cb1-4733-bcab-1810af5469da", value = "tenant id (filterable/sortable)")
  public String getTenantId() {
    return tenantId;
  }

  public void setTenantId(String tenantId) {
    this.tenantId = tenantId;
  }

  public Member legacyId(String legacyId) {
    this.legacyId = legacyId;
    return this;
  }

   /**
   * legacy application id (filterable/sortable)
   * @return legacyId
  **/
  @ApiModelProperty(example = "00000000-0000-0000-0000-000000000000", value = "legacy application id (filterable/sortable)")
  public String getLegacyId() {
    return legacyId;
  }

  public void setLegacyId(String legacyId) {
    this.legacyId = legacyId;
  }

  public Member orgaWhiteList(List<OrganizationIDAccessApi> orgaWhiteList) {
    this.orgaWhiteList = orgaWhiteList;
    return this;
  }

  public Member addOrgaWhiteListItem(OrganizationIDAccessApi orgaWhiteListItem) {
    this.orgaWhiteList.add(orgaWhiteListItem);
    return this;
  }

   /**
   * Get orgaWhiteList
   * @return orgaWhiteList
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<OrganizationIDAccessApi> getOrgaWhiteList() {
    return orgaWhiteList;
  }

  public void setOrgaWhiteList(List<OrganizationIDAccessApi> orgaWhiteList) {
    this.orgaWhiteList = orgaWhiteList;
  }

  public Member id(String id) {
    this.id = id;
    return this;
  }

   /**
   * 
   * @return id
  **/
  @ApiModelProperty(example = "f4206901-c9b2-4e6e-8119-f7d623626060", value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Member name2(String name2) {
    this.name2 = name2;
    return this;
  }

   /**
   * surname (filterable/sortable)
   * @return name2
  **/
  @ApiModelProperty(example = "Name 2", value = "surname (filterable/sortable)")
  public String getName2() {
    return name2;
  }

  public void setName2(String name2) {
    this.name2 = name2;
  }

  public Member name1(String name1) {
    this.name1 = name1;
    return this;
  }

   /**
   * name (filterable/sortable)
   * @return name1
  **/
  @ApiModelProperty(example = "Name 1", value = "name (filterable/sortable)")
  public String getName1() {
    return name1;
  }

  public void setName1(String name1) {
    this.name1 = name1;
  }

  public Member memberRole(Integer memberRole) {
    this.memberRole = memberRole;
    return this;
  }

   /**
   * role (filterable/sortable)
   * @return memberRole
  **/
  @ApiModelProperty(example = "Kanzleisachbearbeiter", required = true, value = "role (filterable/sortable)")
  public Integer getMemberRole() {
    return memberRole;
  }

  public void setMemberRole(Integer memberRole) {
    this.memberRole = memberRole;
  }

  public Member info(String info) {
    this.info = info;
    return this;
  }

   /**
   * name
   * @return info
  **/
  @ApiModelProperty(example = "info", value = "name")
  public String getInfo() {
    return info;
  }

  public void setInfo(String info) {
    this.info = info;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Member member = (Member) o;
    return Objects.equals(this.organisationId, member.organisationId) &&
        Objects.equals(this.portalMemberType, member.portalMemberType) &&
        Objects.equals(this.orga, member.orga) &&
        Objects.equals(this.active, member.active) &&
        Objects.equals(this.parentId, member.parentId) &&
        Objects.equals(this.administrator, member.administrator) &&
        Objects.equals(this.loginName, member.loginName) &&
        Objects.equals(this.legacyMember, member.legacyMember) &&
        Objects.equals(this.portalId, member.portalId) &&
        Objects.equals(this.restrictedToOrganizations, member.restrictedToOrganizations) &&
        Objects.equals(this.groupAccessList, member.groupAccessList) &&
        Objects.equals(this.tenantId, member.tenantId) &&
        Objects.equals(this.legacyId, member.legacyId) &&
        Objects.equals(this.orgaWhiteList, member.orgaWhiteList) &&
        Objects.equals(this.id, member.id) &&
        Objects.equals(this.name2, member.name2) &&
        Objects.equals(this.name1, member.name1) &&
        Objects.equals(this.memberRole, member.memberRole) &&
        Objects.equals(this.info, member.info);
  }

  @Override
  public int hashCode() {
    return Objects.hash(organisationId, portalMemberType, orga, active, parentId, administrator, loginName, legacyMember, portalId, restrictedToOrganizations, groupAccessList, tenantId, legacyId, orgaWhiteList, id, name2, name1, memberRole, info);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Member {\n");
    
    sb.append("    organisationId: ").append(toIndentedString(organisationId)).append("\n");
    sb.append("    portalMemberType: ").append(toIndentedString(portalMemberType)).append("\n");
    sb.append("    orga: ").append(toIndentedString(orga)).append("\n");
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("    parentId: ").append(toIndentedString(parentId)).append("\n");
    sb.append("    administrator: ").append(toIndentedString(administrator)).append("\n");
    sb.append("    loginName: ").append(toIndentedString(loginName)).append("\n");
    sb.append("    legacyMember: ").append(toIndentedString(legacyMember)).append("\n");
    sb.append("    portalId: ").append(toIndentedString(portalId)).append("\n");
    sb.append("    restrictedToOrganizations: ").append(toIndentedString(restrictedToOrganizations)).append("\n");
    sb.append("    groupAccessList: ").append(toIndentedString(groupAccessList)).append("\n");
    sb.append("    tenantId: ").append(toIndentedString(tenantId)).append("\n");
    sb.append("    legacyId: ").append(toIndentedString(legacyId)).append("\n");
    sb.append("    orgaWhiteList: ").append(toIndentedString(orgaWhiteList)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name2: ").append(toIndentedString(name2)).append("\n");
    sb.append("    name1: ").append(toIndentedString(name1)).append("\n");
    sb.append("    memberRole: ").append(toIndentedString(memberRole)).append("\n");
    sb.append("    info: ").append(toIndentedString(info)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

