/**
 * CPM API
 * Public API for CPM
 *
 * OpenAPI spec version: V1.0
 * Contact: info@addison.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package instantreports.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * OrganizationDataApi
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2018-05-03T09:33:53.199+02:00")
public class OrganizationDataApi   {
  @SerializedName("number")
  private String number = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("type")
  private String type = null;

  public OrganizationDataApi number(String number) {
    this.number = number;
    return this;
  }

   /**
   * name of organization (filterable/sortable)
   * @return number
  **/
  @ApiModelProperty(example = "1009111", required = true, value = "name of organization (filterable/sortable)")
  public String getNumber() {
    return number;
  }

  public void setNumber(String number) {
    this.number = number;
  }

  public OrganizationDataApi name(String name) {
    this.name = name;
    return this;
  }

   /**
   * name (filterable/sortable)
   * @return name
  **/
  @ApiModelProperty(example = "Mandant 10099", required = true, value = "name (filterable/sortable)")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public OrganizationDataApi id(String id) {
    this.id = id;
    return this;
  }

   /**
   * id of organization
   * @return id
  **/
  @ApiModelProperty(example = "a6d62ed4-3dbf-45b1-b7c0-37ed6449d253", required = true, value = "id of organization")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public OrganizationDataApi type(String type) {
    this.type = type;
    return this;
  }

   /**
   * type of organization (filterable/sortable)
   * @return type
  **/
  @ApiModelProperty(example = "Mandant", required = true, value = "type of organization (filterable/sortable)")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrganizationDataApi organizationDataApi = (OrganizationDataApi) o;
    return Objects.equals(this.number, organizationDataApi.number) &&
        Objects.equals(this.name, organizationDataApi.name) &&
        Objects.equals(this.id, organizationDataApi.id) &&
        Objects.equals(this.type, organizationDataApi.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(number, name, id, type);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrganizationDataApi {\n");
    
    sb.append("    number: ").append(toIndentedString(number)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

