/**
 * CPM API
 * Public API for CPM
 *
 * OpenAPI spec version: V1.0
 * Contact: info@addison.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package instantreports.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import instantreports.model.DomainDataApi;
import instantreports.model.OrganizationDataApi;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;


/**
 * Organization
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2018-05-03T09:33:53.199+02:00")
public class Organization   {
  @SerializedName("organizationData")
  private OrganizationDataApi organizationData = null;

  @SerializedName("domains")
  private List<DomainDataApi> domains = new ArrayList<DomainDataApi>();

  @SerializedName("id")
  private String id = null;

  public Organization organizationData(OrganizationDataApi organizationData) {
    this.organizationData = organizationData;
    return this;
  }

   /**
   * Get organizationData
   * @return organizationData
  **/
  @ApiModelProperty(example = "null", value = "")
  public OrganizationDataApi getOrganizationData() {
    return organizationData;
  }

  public void setOrganizationData(OrganizationDataApi organizationData) {
    this.organizationData = organizationData;
  }

  public Organization domains(List<DomainDataApi> domains) {
    this.domains = domains;
    return this;
  }

  public Organization addDomainsItem(DomainDataApi domainsItem) {
    this.domains.add(domainsItem);
    return this;
  }

   /**
   * Get domains
   * @return domains
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<DomainDataApi> getDomains() {
    return domains;
  }

  public void setDomains(List<DomainDataApi> domains) {
    this.domains = domains;
  }

  public Organization id(String id) {
    this.id = id;
    return this;
  }

   /**
   * 
   * @return id
  **/
  @ApiModelProperty(example = "f4206901-c9b2-4e6e-8119-f7d623626060", value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Organization organization = (Organization) o;
    return Objects.equals(this.organizationData, organization.organizationData) &&
        Objects.equals(this.domains, organization.domains) &&
        Objects.equals(this.id, organization.id);
  }

  @Override
  public int hashCode() {
    return Objects.hash(organizationData, domains, id);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Organization {\n");
    
    sb.append("    organizationData: ").append(toIndentedString(organizationData)).append("\n");
    sb.append("    domains: ").append(toIndentedString(domains)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

