/**
 * CPM API
 * Public API for CPM
 *
 * OpenAPI spec version: V1.0
 * Contact: info@addison.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package instantreports.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.LocalDate;


/**
 * VermoegenswirksameLeistungenApi
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2018-05-03T09:33:53.199+02:00")
public class VermoegenswirksameLeistungenApi   {
  @SerializedName("vwlEmpfaenger1")
  private String vwlEmpfaenger1 = null;

  @SerializedName("vwlZahlungsbeginn1")
  private LocalDate vwlZahlungsbeginn1 = null;

  @SerializedName("vwlEmpfaenger2")
  private String vwlEmpfaenger2 = null;

  @SerializedName("vwlZahlungsbeginn2")
  private LocalDate vwlZahlungsbeginn2 = null;

  @SerializedName("vwlZahlungsbeginn3")
  private LocalDate vwlZahlungsbeginn3 = null;

  @SerializedName("vwlKontonummer1")
  private String vwlKontonummer1 = null;

  @SerializedName("vwlKontonummer2")
  private String vwlKontonummer2 = null;

  @SerializedName("vwlKontonummer3")
  private String vwlKontonummer3 = null;

  @SerializedName("vwlBankname1")
  private String vwlBankname1 = null;

  @SerializedName("vwlBic2")
  private String vwlBic2 = null;

  @SerializedName("vwlBic1")
  private String vwlBic1 = null;

  @SerializedName("vwlBankname3")
  private String vwlBankname3 = null;

  @SerializedName("vwlBankname2")
  private String vwlBankname2 = null;

  @SerializedName("vwlBic3")
  private String vwlBic3 = null;

  @SerializedName("vwlVertragsnummer3")
  private String vwlVertragsnummer3 = null;

  @SerializedName("vwlVertragsnummer1")
  private String vwlVertragsnummer1 = null;

  @SerializedName("vwlVertragsnummer2")
  private String vwlVertragsnummer2 = null;

  @SerializedName("vwlArbeitgeberanteil1")
  private String vwlArbeitgeberanteil1 = null;

  @SerializedName("vwlBlz2")
  private String vwlBlz2 = null;

  @SerializedName("vwlIban3")
  private String vwlIban3 = null;

  @SerializedName("vwlBlz1")
  private String vwlBlz1 = null;

  @SerializedName("vwlIban1")
  private String vwlIban1 = null;

  @SerializedName("vwlArbeitgeberanteil3")
  private String vwlArbeitgeberanteil3 = null;

  @SerializedName("vwlArbeitgeberanteil2")
  private String vwlArbeitgeberanteil2 = null;

  @SerializedName("vwlIban2")
  private String vwlIban2 = null;

  @SerializedName("vwlBlz3")
  private String vwlBlz3 = null;

  @SerializedName("vwlZahlungsende2")
  private LocalDate vwlZahlungsende2 = null;

  @SerializedName("vwlSparbetrag1")
  private String vwlSparbetrag1 = null;

  @SerializedName("vwlZahlungsende1")
  private LocalDate vwlZahlungsende1 = null;

  @SerializedName("vwlSparbetrag2")
  private String vwlSparbetrag2 = null;

  @SerializedName("vwlSparbetrag3")
  private String vwlSparbetrag3 = null;

  @SerializedName("vwlZahlungsende3")
  private LocalDate vwlZahlungsende3 = null;

  @SerializedName("vwlEmpfaenger3")
  private String vwlEmpfaenger3 = null;

  public VermoegenswirksameLeistungenApi vwlEmpfaenger1(String vwlEmpfaenger1) {
    this.vwlEmpfaenger1 = vwlEmpfaenger1;
    return this;
  }

   /**
   * 
   * @return vwlEmpfaenger1
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getVwlEmpfaenger1() {
    return vwlEmpfaenger1;
  }

  public void setVwlEmpfaenger1(String vwlEmpfaenger1) {
    this.vwlEmpfaenger1 = vwlEmpfaenger1;
  }

  public VermoegenswirksameLeistungenApi vwlZahlungsbeginn1(LocalDate vwlZahlungsbeginn1) {
    this.vwlZahlungsbeginn1 = vwlZahlungsbeginn1;
    return this;
  }

   /**
   * 
   * @return vwlZahlungsbeginn1
  **/
  @ApiModelProperty(example = "null", value = "")
  public LocalDate getVwlZahlungsbeginn1() {
    return vwlZahlungsbeginn1;
  }

  public void setVwlZahlungsbeginn1(LocalDate vwlZahlungsbeginn1) {
    this.vwlZahlungsbeginn1 = vwlZahlungsbeginn1;
  }

  public VermoegenswirksameLeistungenApi vwlEmpfaenger2(String vwlEmpfaenger2) {
    this.vwlEmpfaenger2 = vwlEmpfaenger2;
    return this;
  }

   /**
   * 
   * @return vwlEmpfaenger2
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getVwlEmpfaenger2() {
    return vwlEmpfaenger2;
  }

  public void setVwlEmpfaenger2(String vwlEmpfaenger2) {
    this.vwlEmpfaenger2 = vwlEmpfaenger2;
  }

  public VermoegenswirksameLeistungenApi vwlZahlungsbeginn2(LocalDate vwlZahlungsbeginn2) {
    this.vwlZahlungsbeginn2 = vwlZahlungsbeginn2;
    return this;
  }

   /**
   * 
   * @return vwlZahlungsbeginn2
  **/
  @ApiModelProperty(example = "null", value = "")
  public LocalDate getVwlZahlungsbeginn2() {
    return vwlZahlungsbeginn2;
  }

  public void setVwlZahlungsbeginn2(LocalDate vwlZahlungsbeginn2) {
    this.vwlZahlungsbeginn2 = vwlZahlungsbeginn2;
  }

  public VermoegenswirksameLeistungenApi vwlZahlungsbeginn3(LocalDate vwlZahlungsbeginn3) {
    this.vwlZahlungsbeginn3 = vwlZahlungsbeginn3;
    return this;
  }

   /**
   * 
   * @return vwlZahlungsbeginn3
  **/
  @ApiModelProperty(example = "null", value = "")
  public LocalDate getVwlZahlungsbeginn3() {
    return vwlZahlungsbeginn3;
  }

  public void setVwlZahlungsbeginn3(LocalDate vwlZahlungsbeginn3) {
    this.vwlZahlungsbeginn3 = vwlZahlungsbeginn3;
  }

  public VermoegenswirksameLeistungenApi vwlKontonummer1(String vwlKontonummer1) {
    this.vwlKontonummer1 = vwlKontonummer1;
    return this;
  }

   /**
   * 
   * @return vwlKontonummer1
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getVwlKontonummer1() {
    return vwlKontonummer1;
  }

  public void setVwlKontonummer1(String vwlKontonummer1) {
    this.vwlKontonummer1 = vwlKontonummer1;
  }

  public VermoegenswirksameLeistungenApi vwlKontonummer2(String vwlKontonummer2) {
    this.vwlKontonummer2 = vwlKontonummer2;
    return this;
  }

   /**
   * 
   * @return vwlKontonummer2
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getVwlKontonummer2() {
    return vwlKontonummer2;
  }

  public void setVwlKontonummer2(String vwlKontonummer2) {
    this.vwlKontonummer2 = vwlKontonummer2;
  }

  public VermoegenswirksameLeistungenApi vwlKontonummer3(String vwlKontonummer3) {
    this.vwlKontonummer3 = vwlKontonummer3;
    return this;
  }

   /**
   * 
   * @return vwlKontonummer3
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getVwlKontonummer3() {
    return vwlKontonummer3;
  }

  public void setVwlKontonummer3(String vwlKontonummer3) {
    this.vwlKontonummer3 = vwlKontonummer3;
  }

  public VermoegenswirksameLeistungenApi vwlBankname1(String vwlBankname1) {
    this.vwlBankname1 = vwlBankname1;
    return this;
  }

   /**
   * 
   * @return vwlBankname1
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getVwlBankname1() {
    return vwlBankname1;
  }

  public void setVwlBankname1(String vwlBankname1) {
    this.vwlBankname1 = vwlBankname1;
  }

  public VermoegenswirksameLeistungenApi vwlBic2(String vwlBic2) {
    this.vwlBic2 = vwlBic2;
    return this;
  }

   /**
   * 
   * @return vwlBic2
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getVwlBic2() {
    return vwlBic2;
  }

  public void setVwlBic2(String vwlBic2) {
    this.vwlBic2 = vwlBic2;
  }

  public VermoegenswirksameLeistungenApi vwlBic1(String vwlBic1) {
    this.vwlBic1 = vwlBic1;
    return this;
  }

   /**
   * 
   * @return vwlBic1
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getVwlBic1() {
    return vwlBic1;
  }

  public void setVwlBic1(String vwlBic1) {
    this.vwlBic1 = vwlBic1;
  }

  public VermoegenswirksameLeistungenApi vwlBankname3(String vwlBankname3) {
    this.vwlBankname3 = vwlBankname3;
    return this;
  }

   /**
   * 
   * @return vwlBankname3
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getVwlBankname3() {
    return vwlBankname3;
  }

  public void setVwlBankname3(String vwlBankname3) {
    this.vwlBankname3 = vwlBankname3;
  }

  public VermoegenswirksameLeistungenApi vwlBankname2(String vwlBankname2) {
    this.vwlBankname2 = vwlBankname2;
    return this;
  }

   /**
   * 
   * @return vwlBankname2
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getVwlBankname2() {
    return vwlBankname2;
  }

  public void setVwlBankname2(String vwlBankname2) {
    this.vwlBankname2 = vwlBankname2;
  }

  public VermoegenswirksameLeistungenApi vwlBic3(String vwlBic3) {
    this.vwlBic3 = vwlBic3;
    return this;
  }

   /**
   * 
   * @return vwlBic3
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getVwlBic3() {
    return vwlBic3;
  }

  public void setVwlBic3(String vwlBic3) {
    this.vwlBic3 = vwlBic3;
  }

  public VermoegenswirksameLeistungenApi vwlVertragsnummer3(String vwlVertragsnummer3) {
    this.vwlVertragsnummer3 = vwlVertragsnummer3;
    return this;
  }

   /**
   * 
   * @return vwlVertragsnummer3
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getVwlVertragsnummer3() {
    return vwlVertragsnummer3;
  }

  public void setVwlVertragsnummer3(String vwlVertragsnummer3) {
    this.vwlVertragsnummer3 = vwlVertragsnummer3;
  }

  public VermoegenswirksameLeistungenApi vwlVertragsnummer1(String vwlVertragsnummer1) {
    this.vwlVertragsnummer1 = vwlVertragsnummer1;
    return this;
  }

   /**
   * 
   * @return vwlVertragsnummer1
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getVwlVertragsnummer1() {
    return vwlVertragsnummer1;
  }

  public void setVwlVertragsnummer1(String vwlVertragsnummer1) {
    this.vwlVertragsnummer1 = vwlVertragsnummer1;
  }

  public VermoegenswirksameLeistungenApi vwlVertragsnummer2(String vwlVertragsnummer2) {
    this.vwlVertragsnummer2 = vwlVertragsnummer2;
    return this;
  }

   /**
   * 
   * @return vwlVertragsnummer2
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getVwlVertragsnummer2() {
    return vwlVertragsnummer2;
  }

  public void setVwlVertragsnummer2(String vwlVertragsnummer2) {
    this.vwlVertragsnummer2 = vwlVertragsnummer2;
  }

  public VermoegenswirksameLeistungenApi vwlArbeitgeberanteil1(String vwlArbeitgeberanteil1) {
    this.vwlArbeitgeberanteil1 = vwlArbeitgeberanteil1;
    return this;
  }

   /**
   * 
   * @return vwlArbeitgeberanteil1
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getVwlArbeitgeberanteil1() {
    return vwlArbeitgeberanteil1;
  }

  public void setVwlArbeitgeberanteil1(String vwlArbeitgeberanteil1) {
    this.vwlArbeitgeberanteil1 = vwlArbeitgeberanteil1;
  }

  public VermoegenswirksameLeistungenApi vwlBlz2(String vwlBlz2) {
    this.vwlBlz2 = vwlBlz2;
    return this;
  }

   /**
   * 
   * @return vwlBlz2
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getVwlBlz2() {
    return vwlBlz2;
  }

  public void setVwlBlz2(String vwlBlz2) {
    this.vwlBlz2 = vwlBlz2;
  }

  public VermoegenswirksameLeistungenApi vwlIban3(String vwlIban3) {
    this.vwlIban3 = vwlIban3;
    return this;
  }

   /**
   * 
   * @return vwlIban3
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getVwlIban3() {
    return vwlIban3;
  }

  public void setVwlIban3(String vwlIban3) {
    this.vwlIban3 = vwlIban3;
  }

  public VermoegenswirksameLeistungenApi vwlBlz1(String vwlBlz1) {
    this.vwlBlz1 = vwlBlz1;
    return this;
  }

   /**
   * 
   * @return vwlBlz1
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getVwlBlz1() {
    return vwlBlz1;
  }

  public void setVwlBlz1(String vwlBlz1) {
    this.vwlBlz1 = vwlBlz1;
  }

  public VermoegenswirksameLeistungenApi vwlIban1(String vwlIban1) {
    this.vwlIban1 = vwlIban1;
    return this;
  }

   /**
   * 
   * @return vwlIban1
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getVwlIban1() {
    return vwlIban1;
  }

  public void setVwlIban1(String vwlIban1) {
    this.vwlIban1 = vwlIban1;
  }

  public VermoegenswirksameLeistungenApi vwlArbeitgeberanteil3(String vwlArbeitgeberanteil3) {
    this.vwlArbeitgeberanteil3 = vwlArbeitgeberanteil3;
    return this;
  }

   /**
   * 
   * @return vwlArbeitgeberanteil3
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getVwlArbeitgeberanteil3() {
    return vwlArbeitgeberanteil3;
  }

  public void setVwlArbeitgeberanteil3(String vwlArbeitgeberanteil3) {
    this.vwlArbeitgeberanteil3 = vwlArbeitgeberanteil3;
  }

  public VermoegenswirksameLeistungenApi vwlArbeitgeberanteil2(String vwlArbeitgeberanteil2) {
    this.vwlArbeitgeberanteil2 = vwlArbeitgeberanteil2;
    return this;
  }

   /**
   * 
   * @return vwlArbeitgeberanteil2
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getVwlArbeitgeberanteil2() {
    return vwlArbeitgeberanteil2;
  }

  public void setVwlArbeitgeberanteil2(String vwlArbeitgeberanteil2) {
    this.vwlArbeitgeberanteil2 = vwlArbeitgeberanteil2;
  }

  public VermoegenswirksameLeistungenApi vwlIban2(String vwlIban2) {
    this.vwlIban2 = vwlIban2;
    return this;
  }

   /**
   * 
   * @return vwlIban2
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getVwlIban2() {
    return vwlIban2;
  }

  public void setVwlIban2(String vwlIban2) {
    this.vwlIban2 = vwlIban2;
  }

  public VermoegenswirksameLeistungenApi vwlBlz3(String vwlBlz3) {
    this.vwlBlz3 = vwlBlz3;
    return this;
  }

   /**
   * 
   * @return vwlBlz3
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getVwlBlz3() {
    return vwlBlz3;
  }

  public void setVwlBlz3(String vwlBlz3) {
    this.vwlBlz3 = vwlBlz3;
  }

  public VermoegenswirksameLeistungenApi vwlZahlungsende2(LocalDate vwlZahlungsende2) {
    this.vwlZahlungsende2 = vwlZahlungsende2;
    return this;
  }

   /**
   * 
   * @return vwlZahlungsende2
  **/
  @ApiModelProperty(example = "null", value = "")
  public LocalDate getVwlZahlungsende2() {
    return vwlZahlungsende2;
  }

  public void setVwlZahlungsende2(LocalDate vwlZahlungsende2) {
    this.vwlZahlungsende2 = vwlZahlungsende2;
  }

  public VermoegenswirksameLeistungenApi vwlSparbetrag1(String vwlSparbetrag1) {
    this.vwlSparbetrag1 = vwlSparbetrag1;
    return this;
  }

   /**
   * 
   * @return vwlSparbetrag1
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getVwlSparbetrag1() {
    return vwlSparbetrag1;
  }

  public void setVwlSparbetrag1(String vwlSparbetrag1) {
    this.vwlSparbetrag1 = vwlSparbetrag1;
  }

  public VermoegenswirksameLeistungenApi vwlZahlungsende1(LocalDate vwlZahlungsende1) {
    this.vwlZahlungsende1 = vwlZahlungsende1;
    return this;
  }

   /**
   * 
   * @return vwlZahlungsende1
  **/
  @ApiModelProperty(example = "null", value = "")
  public LocalDate getVwlZahlungsende1() {
    return vwlZahlungsende1;
  }

  public void setVwlZahlungsende1(LocalDate vwlZahlungsende1) {
    this.vwlZahlungsende1 = vwlZahlungsende1;
  }

  public VermoegenswirksameLeistungenApi vwlSparbetrag2(String vwlSparbetrag2) {
    this.vwlSparbetrag2 = vwlSparbetrag2;
    return this;
  }

   /**
   * 
   * @return vwlSparbetrag2
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getVwlSparbetrag2() {
    return vwlSparbetrag2;
  }

  public void setVwlSparbetrag2(String vwlSparbetrag2) {
    this.vwlSparbetrag2 = vwlSparbetrag2;
  }

  public VermoegenswirksameLeistungenApi vwlSparbetrag3(String vwlSparbetrag3) {
    this.vwlSparbetrag3 = vwlSparbetrag3;
    return this;
  }

   /**
   * 
   * @return vwlSparbetrag3
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getVwlSparbetrag3() {
    return vwlSparbetrag3;
  }

  public void setVwlSparbetrag3(String vwlSparbetrag3) {
    this.vwlSparbetrag3 = vwlSparbetrag3;
  }

  public VermoegenswirksameLeistungenApi vwlZahlungsende3(LocalDate vwlZahlungsende3) {
    this.vwlZahlungsende3 = vwlZahlungsende3;
    return this;
  }

   /**
   * 
   * @return vwlZahlungsende3
  **/
  @ApiModelProperty(example = "null", value = "")
  public LocalDate getVwlZahlungsende3() {
    return vwlZahlungsende3;
  }

  public void setVwlZahlungsende3(LocalDate vwlZahlungsende3) {
    this.vwlZahlungsende3 = vwlZahlungsende3;
  }

  public VermoegenswirksameLeistungenApi vwlEmpfaenger3(String vwlEmpfaenger3) {
    this.vwlEmpfaenger3 = vwlEmpfaenger3;
    return this;
  }

   /**
   * 
   * @return vwlEmpfaenger3
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getVwlEmpfaenger3() {
    return vwlEmpfaenger3;
  }

  public void setVwlEmpfaenger3(String vwlEmpfaenger3) {
    this.vwlEmpfaenger3 = vwlEmpfaenger3;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VermoegenswirksameLeistungenApi vermoegenswirksameLeistungenApi = (VermoegenswirksameLeistungenApi) o;
    return Objects.equals(this.vwlEmpfaenger1, vermoegenswirksameLeistungenApi.vwlEmpfaenger1) &&
        Objects.equals(this.vwlZahlungsbeginn1, vermoegenswirksameLeistungenApi.vwlZahlungsbeginn1) &&
        Objects.equals(this.vwlEmpfaenger2, vermoegenswirksameLeistungenApi.vwlEmpfaenger2) &&
        Objects.equals(this.vwlZahlungsbeginn2, vermoegenswirksameLeistungenApi.vwlZahlungsbeginn2) &&
        Objects.equals(this.vwlZahlungsbeginn3, vermoegenswirksameLeistungenApi.vwlZahlungsbeginn3) &&
        Objects.equals(this.vwlKontonummer1, vermoegenswirksameLeistungenApi.vwlKontonummer1) &&
        Objects.equals(this.vwlKontonummer2, vermoegenswirksameLeistungenApi.vwlKontonummer2) &&
        Objects.equals(this.vwlKontonummer3, vermoegenswirksameLeistungenApi.vwlKontonummer3) &&
        Objects.equals(this.vwlBankname1, vermoegenswirksameLeistungenApi.vwlBankname1) &&
        Objects.equals(this.vwlBic2, vermoegenswirksameLeistungenApi.vwlBic2) &&
        Objects.equals(this.vwlBic1, vermoegenswirksameLeistungenApi.vwlBic1) &&
        Objects.equals(this.vwlBankname3, vermoegenswirksameLeistungenApi.vwlBankname3) &&
        Objects.equals(this.vwlBankname2, vermoegenswirksameLeistungenApi.vwlBankname2) &&
        Objects.equals(this.vwlBic3, vermoegenswirksameLeistungenApi.vwlBic3) &&
        Objects.equals(this.vwlVertragsnummer3, vermoegenswirksameLeistungenApi.vwlVertragsnummer3) &&
        Objects.equals(this.vwlVertragsnummer1, vermoegenswirksameLeistungenApi.vwlVertragsnummer1) &&
        Objects.equals(this.vwlVertragsnummer2, vermoegenswirksameLeistungenApi.vwlVertragsnummer2) &&
        Objects.equals(this.vwlArbeitgeberanteil1, vermoegenswirksameLeistungenApi.vwlArbeitgeberanteil1) &&
        Objects.equals(this.vwlBlz2, vermoegenswirksameLeistungenApi.vwlBlz2) &&
        Objects.equals(this.vwlIban3, vermoegenswirksameLeistungenApi.vwlIban3) &&
        Objects.equals(this.vwlBlz1, vermoegenswirksameLeistungenApi.vwlBlz1) &&
        Objects.equals(this.vwlIban1, vermoegenswirksameLeistungenApi.vwlIban1) &&
        Objects.equals(this.vwlArbeitgeberanteil3, vermoegenswirksameLeistungenApi.vwlArbeitgeberanteil3) &&
        Objects.equals(this.vwlArbeitgeberanteil2, vermoegenswirksameLeistungenApi.vwlArbeitgeberanteil2) &&
        Objects.equals(this.vwlIban2, vermoegenswirksameLeistungenApi.vwlIban2) &&
        Objects.equals(this.vwlBlz3, vermoegenswirksameLeistungenApi.vwlBlz3) &&
        Objects.equals(this.vwlZahlungsende2, vermoegenswirksameLeistungenApi.vwlZahlungsende2) &&
        Objects.equals(this.vwlSparbetrag1, vermoegenswirksameLeistungenApi.vwlSparbetrag1) &&
        Objects.equals(this.vwlZahlungsende1, vermoegenswirksameLeistungenApi.vwlZahlungsende1) &&
        Objects.equals(this.vwlSparbetrag2, vermoegenswirksameLeistungenApi.vwlSparbetrag2) &&
        Objects.equals(this.vwlSparbetrag3, vermoegenswirksameLeistungenApi.vwlSparbetrag3) &&
        Objects.equals(this.vwlZahlungsende3, vermoegenswirksameLeistungenApi.vwlZahlungsende3) &&
        Objects.equals(this.vwlEmpfaenger3, vermoegenswirksameLeistungenApi.vwlEmpfaenger3);
  }

  @Override
  public int hashCode() {
    return Objects.hash(vwlEmpfaenger1, vwlZahlungsbeginn1, vwlEmpfaenger2, vwlZahlungsbeginn2, vwlZahlungsbeginn3, vwlKontonummer1, vwlKontonummer2, vwlKontonummer3, vwlBankname1, vwlBic2, vwlBic1, vwlBankname3, vwlBankname2, vwlBic3, vwlVertragsnummer3, vwlVertragsnummer1, vwlVertragsnummer2, vwlArbeitgeberanteil1, vwlBlz2, vwlIban3, vwlBlz1, vwlIban1, vwlArbeitgeberanteil3, vwlArbeitgeberanteil2, vwlIban2, vwlBlz3, vwlZahlungsende2, vwlSparbetrag1, vwlZahlungsende1, vwlSparbetrag2, vwlSparbetrag3, vwlZahlungsende3, vwlEmpfaenger3);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VermoegenswirksameLeistungenApi {\n");
    
    sb.append("    vwlEmpfaenger1: ").append(toIndentedString(vwlEmpfaenger1)).append("\n");
    sb.append("    vwlZahlungsbeginn1: ").append(toIndentedString(vwlZahlungsbeginn1)).append("\n");
    sb.append("    vwlEmpfaenger2: ").append(toIndentedString(vwlEmpfaenger2)).append("\n");
    sb.append("    vwlZahlungsbeginn2: ").append(toIndentedString(vwlZahlungsbeginn2)).append("\n");
    sb.append("    vwlZahlungsbeginn3: ").append(toIndentedString(vwlZahlungsbeginn3)).append("\n");
    sb.append("    vwlKontonummer1: ").append(toIndentedString(vwlKontonummer1)).append("\n");
    sb.append("    vwlKontonummer2: ").append(toIndentedString(vwlKontonummer2)).append("\n");
    sb.append("    vwlKontonummer3: ").append(toIndentedString(vwlKontonummer3)).append("\n");
    sb.append("    vwlBankname1: ").append(toIndentedString(vwlBankname1)).append("\n");
    sb.append("    vwlBic2: ").append(toIndentedString(vwlBic2)).append("\n");
    sb.append("    vwlBic1: ").append(toIndentedString(vwlBic1)).append("\n");
    sb.append("    vwlBankname3: ").append(toIndentedString(vwlBankname3)).append("\n");
    sb.append("    vwlBankname2: ").append(toIndentedString(vwlBankname2)).append("\n");
    sb.append("    vwlBic3: ").append(toIndentedString(vwlBic3)).append("\n");
    sb.append("    vwlVertragsnummer3: ").append(toIndentedString(vwlVertragsnummer3)).append("\n");
    sb.append("    vwlVertragsnummer1: ").append(toIndentedString(vwlVertragsnummer1)).append("\n");
    sb.append("    vwlVertragsnummer2: ").append(toIndentedString(vwlVertragsnummer2)).append("\n");
    sb.append("    vwlArbeitgeberanteil1: ").append(toIndentedString(vwlArbeitgeberanteil1)).append("\n");
    sb.append("    vwlBlz2: ").append(toIndentedString(vwlBlz2)).append("\n");
    sb.append("    vwlIban3: ").append(toIndentedString(vwlIban3)).append("\n");
    sb.append("    vwlBlz1: ").append(toIndentedString(vwlBlz1)).append("\n");
    sb.append("    vwlIban1: ").append(toIndentedString(vwlIban1)).append("\n");
    sb.append("    vwlArbeitgeberanteil3: ").append(toIndentedString(vwlArbeitgeberanteil3)).append("\n");
    sb.append("    vwlArbeitgeberanteil2: ").append(toIndentedString(vwlArbeitgeberanteil2)).append("\n");
    sb.append("    vwlIban2: ").append(toIndentedString(vwlIban2)).append("\n");
    sb.append("    vwlBlz3: ").append(toIndentedString(vwlBlz3)).append("\n");
    sb.append("    vwlZahlungsende2: ").append(toIndentedString(vwlZahlungsende2)).append("\n");
    sb.append("    vwlSparbetrag1: ").append(toIndentedString(vwlSparbetrag1)).append("\n");
    sb.append("    vwlZahlungsende1: ").append(toIndentedString(vwlZahlungsende1)).append("\n");
    sb.append("    vwlSparbetrag2: ").append(toIndentedString(vwlSparbetrag2)).append("\n");
    sb.append("    vwlSparbetrag3: ").append(toIndentedString(vwlSparbetrag3)).append("\n");
    sb.append("    vwlZahlungsende3: ").append(toIndentedString(vwlZahlungsende3)).append("\n");
    sb.append("    vwlEmpfaenger3: ").append(toIndentedString(vwlEmpfaenger3)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

